### ISSUE TITLE
Crash when using k8s.yaml.ConfigFile

### ISSUE THREAD

**Issue by alex-hunt-materialize** [pulumi/pulumi#10281]
### What happened?

Using the `k8s.yaml.ConfigFile` resource crashes during `pulumi up`.

```
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/alex/.pulumi/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
        return future.result()
      File "/home/alex/git2/cloud/venv/lib64/python3.9/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/alex/git2/cloud/venv/lib64/python3.9/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/home/alex/git2/cloud/venv/lib64/python3.9/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/home/alex/git2/cloud/venv/lib64/python3.9/site-packages/pulumi/runtime/stack.py", line 149, in __init__
        func()
      File "/home/alex/.pulumi/bin/pulumi-language-python-exec", line 106, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/lib64/python3.9/runpy.py", line 288, in run_path
        return _run_module_code(code, init_globals, run_name,
      File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "pulumi_main.py", line 27, in <module>
        from infra import regions as _
      File "/home/alex/git2/cloud/./infra/regions.py", line 166, in <module>
        Region(
      File "/home/alex/git2/cloud/./infra/regions.py", line 127, in __init__
        CertManager(cluster, cluster_dns_zone.provision_zone)
      File "/home/alex/git2/cloud/./infra/tls.py", line 40, in __init__
        self.crds = k8s.yaml.ConfigFile(
      File "/home/alex/git2/cloud/venv/lib64/python3.9/site-packages/pulumi_kubernetes/yaml/yaml.py", line 380, in __init__
        __ret__ = invoked.value["result"]
    TypeError: 'NoneType' object is not subscriptable
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

### Steps to reproduce

The following code triggers it when using pulumi-kubernetes 3.20.0 or 3.20.1:
```python3
self.crds = k8s.yaml.ConfigFile(
    "cert-manager-crds",
    file="https://github.com/jetstack/cert-manager/releases/download/v1.8.1/cert-manager.crds.yaml",
    opts=pulumi.ResourceOptions(
        parent=self,
        provider=cluster.provider,
    ),
)
```

Note that this does not happen if the resource is initially created with an older version (confirmed with 3.19.1) and then upgraded to the new provider.

### Expected Behavior

Pulumi should create the resources defined in the yaml file in the kubernetes cluster specified by the provider in the ResourceOptions.

### Actual Behavior

Pulumi crashes in the preview.

### Versions used

```
CLI          
Version      3.34.1
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME              VERSION
aws               5.9.1
cloudinit         1.3.0
command           0.2.0
docker-buildkit   0.1.17
eks               0.40.0
fivetran          0.1.6
frontegg          0.2.22
honeycomb         0.0.11
kubernetes        3.20.0
kubernetes-proxy  0.1.3
linkerd-link      0.0.7
postgresql        3.5.0
postgresql-exec   0.1.1
python            unknown
random            4.7.0
tls               4.6.0

Host     
OS       fedora
Version  35
Arch     x86_64

This project is written in python: executable='/home/alex/git3/cloud/venv/bin/python3' version='3.9.13'

{{Stack output redacted because it's huge.}}

Dependencies:
NAME                                 VERSION
analytics-python                     1.4.0
black                                22.6.0
boto3                                1.24.26
boto3-stubs                          1.24.26
cryptography-347-stubs               1.0.0
dj-database-url                      0.5.0
django-csp                           3.7
django-migrations-formatter          1.0.0
django-proxy                         1.2.1
django-ratelimit                     3.0.1
django-simple-history                3.1.1
django-types                         0.15.0
djangorestframework-camel-case       1.3.0
djangorestframework-types            0.7.0
docker-image-py                      0.1.12
drf-spectacular                      0.22.1
gunicorn                             20.1.0
honeycomb-stubs                      0.2.2
isort                                5.10.1
jwcrypto                             1.3.1
kubernetes                           21.7.0
kubernetes-stubs                     21.7.0
mypy-boto3-ec2                       1.24.32
mypy-boto3-elb                       1.24.0
mypy-boto3-elbv2                     1.24.20.post14
mypy-boto3-resourcegroupstaggingapi  1.24.0
mypy-boto3-route53                   1.24.1
mypy-boto3-s3                        1.24.0
mypy-boto3-sts                       1.24.0
oauth2client                         4.1.3
pip                                  22.1.2
pre-commit                           2.19.0
psycopg2                             2.9.3
pulumi-cloudinit                     1.3.0
pulumi-command                       0.2.0
pulumi-docker-buildkit               0.1.17
pulumi-eks                           0.40.0
pulumi-fivetran                      0.1.6
pulumi-frontegg                      0.2.22
pulumi-honeycomb                     0.0.11
pulumi-kubernetes-proxy              0.1.3
pulumi-linkerd-link                  0.0.7
pulumi-postgresql                    3.5.0
pulumi-postgresql-exec               0.1.1
pulumi-random                        4.7.0
pulumi-tls                           4.6.0
pydantic                             1.9.1
pyOpenSSL                            22.0.0
python-json-logger                   2.0.2
pytz                                 2022.1
sentry-sdk                           1.5.12
slack-sdk                            3.16.2
timeout-decorator                    0.5.0
types-cachetools                     5.2.1
types-pyOpenSSL                      22.0.3
wheel                                0.37.1
whitenoise                           6.2.0
```

### Additional context

This seems very similar (possible duplicate?) to https://github.com/pulumi/pulumi-kubernetes/issues/2038 , but that one is in typescript, so it's hard to tell.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
@pulumi/platform I'm pretty sure this issue has something to do with the gRPC layer in the Python SDK. I haven't been able to find a root cause in the k8s provider, so I'm transferring the issue here.

**Comment by Frassle** [comment]
Tried bumping our "large resource" tests to send 72Mb of data and to call an invoke from python and that all seems to be working, so something more complex than just size going on here.

**Comment by Frassle** [comment]
OK this is recursion depth again. Make an array nested a few hundred times and trying to send it over grpc causes python to crash out.

**Comment by Frassle** [comment]
Got a simple test in pulumi/pulumi that repros this: https://github.com/pulumi/pulumi/pull/10284

Just need to work out how to get protobuf to actually increase the limit, our old code to do this isn't working anymore: https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/runtime/invoke.py#L33-L53

**Comment by Frassle** [comment]
Found the right import for the new library, https://github.com/pulumi/pulumi/pull/10284 should fix this.

**Comment by jsia9** [comment]
im still getting the error 
`Exception: invoke of kubernetes:yaml:decode failed: invocation of kubernetes:yaml:decode returned an error: unrecognized data function (Invoke): kubernetes:yaml:decode`

```
Dependencies:
NAME                 VERSION
boto3                1.24.49
dnspython            2.2.1
flake8               5.0.4
pip                  22.2.2
pulumi-aiven         5.2.0
pulumi-azure-native  1.67.0
pulumi-azuread       5.26.1
pulumi-eks           0.41.2
pulumi-opsgenie      1.1.8
pulumi-random        4.8.1
pulumi-tls           4.6.0
setuptools           63.4.3
wheel                0.37.1

```

pip env

```
venv/bin/pip list                                                                                       
Package             Version
------------------- ---------
Arpeggio            1.10.2
attrs               22.1.0
boto3               1.24.49
botocore            1.27.49
certifi             2022.6.15
charset-normalizer  2.1.0
dill                0.3.5.1
dnspython           2.2.1
flake8              5.0.4
grpcio              1.47.0
idna                3.3
jmespath            1.0.1
mccabe              0.7.0
parver              0.3.1
pip                 22.2.2
protobuf            4.21.5
pulumi              3.37.2
pulumi-aiven        5.2.0
pulumi-aws          5.10.0
pulumi-azure-native 1.67.0
pulumi-azuread      5.26.1
pulumi-eks          0.41.2
pulumi-kubernetes   3.20.3
pulumi-opsgenie     1.1.8
pulumi-random       4.8.1
pulumi-tls          4.6.0
pycodestyle         2.9.1
pyflakes            2.5.0
python-dateutil     2.8.2
PyYAML              5.4.1
requests            2.28.1
s3transfer          0.6.0
semver              2.13.0
setuptools          63.4.3
six                 1.16.0
urllib3             1.26.11
wheel               0.37.1
```

**Comment by AaronFriel** [comment]
We think this may be an issue with grpcio, can you pin `grpcio==1.47` in your requirements.txt and reinstall?

If you still encounter the issue, let's reopen and track the grpc bug. 

CC @Frassle

**Comment by jsia9** [comment]
thank you @AaronFriel  for your quick reply. 
I was looking at the requirements.txt and it already has the version `grpcio              1.47.0`. I did a reinstall just in case and reran pulumi up but I am getting the same error.

```
        kubernetes.yaml.ConfigFile(
      File "/Users/stone/pulumi/venv/lib/python3.10/site-packages/pulumi_kubernetes/yaml/yaml.py", line 348, in __init__
        __ret__ = pulumi.runtime.invoke('kubernetes:yaml:decode', {'text': text}, invoke_opts).value['result']
      File "/Users/stone/pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/invoke.py", line 144, in invoke
        raise invoke_error
    Exception: invoke of kubernetes:yaml:decode failed: invocation of kubernetes:yaml:decode returned an error: unrecognized data function (Invoke): kubernetes:yaml:decode
```

**Comment by AaronFriel** [comment]
@Frassle I'm reopening for now, pending your update. I'm not sure about resolution.

**Comment by mikhailshilkov** [comment]
@AaronFriel This looks like a different error, I think we should open a new issue for it. Based on

> unrecognized data function (Invoke)

I would guess that this call gets to the AWS provider and triggers the error [here](https://github.com/pulumi/pulumi-terraform-bridge/blob/a95d21273ce0e0554e000e1e2ef849e15eafc013/pkg/tfbridge/provider.go#L1141), instead of coming to the k8s provider.

@jsia9 I think this like is wrong: `provider=aws_account.provider(),` and you should be passing an instance of `kubernetes` provider instead. If that doesn't help, please open a new issue.

**Comment by jsia9** [comment]
figured out the issue was finally related to the k8s provider used. If some-one encounters the same error, there is , as of today an open bug [with a work around here](https://github.com/pulumi/pulumi-eks/issues/662#issuecomment-1048339088).

**Comment by danylo-omelchenko** [comment]
I still experience that issue. My case that I'm creating cluster and applying yaml.ConfigFile at the same program, so if on the stage of running pulumi preview, cluster and there fore kubeconfig doesn't exist it fails.

[this workaround](https://github.com/pulumi/pulumi-eks/issues/662#issuecomment-1048339088) nudged me into the direction of digging.

The difference lies in the yaml.py:

working version of `pulumi-kubernetes<=3.19.1` haven't used provider to construct invode_opts:
```python
invoke_opts = pulumi.InvokeOptions(version=_utilities.get_version())

__ret__ = pulumi.runtime.invoke('kubernetes:yaml:decode', {'text': text}, invoke_opts).value['result']
```

but new does:
```python
invoke_opts = pulumi.InvokeOptions(
    version=_utilities.get_version(), 
    provider=opts.provider if opts.provider else None)

__ret__ = pulumi.runtime.invoke('kubernetes:yaml:decode', {'text': text}, invoke_opts).value['result']
```

In my case I work with GKE so I construct my kubeconfig on my own:
```python

def kubeconfig_generator(args):
    name, endpoint, master_auth, project, location = args
    context = f"{project}_{location}_{name}"
    return f"""
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {master_auth.get('cluster_ca_certificate')}
    server: https://{endpoint}
  name: {context}
contexts:
- context:
    cluster: {context}
    user: {context}
  name: {context}
current-context: {context}
kind: Config
preferences: {{}}
users:
- name: {context}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      interactiveMode: IfAvailable
      provideClusterInfo: true
    """

kubeconfig = pulumi.Output.all(
           cluster.name, cluster.endpoint, cluster.master_auth, cluster.project, cluster.location
        ).apply(kubeconfig_generator)
        
k8s_provider = k8s.Provider(
            "k8s-provider",
            kubeconfig=kubeconfig,
            opts=pulumi.ResourceOptions(
                depends_on=[cluster]))
                
config = k8s.yaml.ConfigFile(
            'knative-operator',
            file=pulumi_knative.info.ULR,
            opts=pulumi.ResourceOptions(
                depends_on=[k8s_provider],
                provider=k8s_provider))
```

**Comment by viveklak** [comment]
@danylo-omelchenko The issue you are seeing is discussed in https://github.com/pulumi/pulumi-kubernetes/issues/2038. For the timebeing, you might want to consider splitting your kubernetes code to a separate dependent stack using a stack reference: https://www.pulumi.com/docs/intro/concepts/stack/#stackreferences. Alternatively, you could consider creating  the configfile resource in an apply block but that comes with the downside of not having previews on the configfile resources. We are still looking at alternatives for the above issue at the moment.

**Comment by Frassle** [comment]
@ocervell this issue is quite old at this point, best to raise a new issue in the Kubernetes repo explaining your case and just reference back to this one.
