### ISSUE TITLE
"--target-dependents" flag when invoking "pulumi up" targets far too many resources

### ISSUE THREAD

**Issue by chomey** [pulumi/pulumi#13591]
### What happened?

The `--target-dependents` flag does not actually target dependents as we would expect. 

We have the following stack, with the following dependencies.

`a` -> `b` -> `c`, and `d` as a stand alone resource.

When targetting `b` with `--target-dependents`, I would expect `b` and `c` to be queued for an update, and nothing else.

Stack:
```
	a, err := random.NewRandomInteger(ctx, "a", &random.RandomIntegerArgs{
		Max:  pulumi.Int(10000),
		Min:  pulumi.Int(1),
		Seed: pulumi.Sprintf("%s", time.Now().String()),
	})
	if err != nil {
		return err
	}

	b, err := random.NewRandomInteger(ctx, "b", &random.RandomIntegerArgs{
		Max:  pulumi.Int(10000),
		Min:  pulumi.Int(1),
		Seed: pulumi.Sprintf("%s", time.Now().String(), a.Result),
	})
	if err != nil {
		return err
	}

	_, err = random.NewRandomInteger(ctx, "c", &random.RandomIntegerArgs{
		Max:  pulumi.Int(10000),
		Min:  pulumi.Int(1),
		Seed: pulumi.Sprintf("%s%d", time.Now().String(), b.Result),
	})
	if err != nil {
		return err
	}

	_, err = random.NewRandomInteger(ctx, "d", &random.RandomIntegerArgs{
		Max:  pulumi.Int(10000),
		Min:  pulumi.Int(1),
		Seed: pulumi.Sprintf("%s", time.Now().String()),
	})
	if err != nil {
		return err
	}
```

Note that with the `Seed` parameter is changing for all 4 resources, which means all 4 should be updated in normal `pulumi up` conditions

The following happens:
```
» pulumi up -t 'urn:pulumi:scratch::pragma::random:index/randomInteger:RandomInteger::b' --target-dependents
Previewing update (scratch):
     Type                           Name            Plan        Info
     pulumi:pulumi:Stack            pragma-scratch              
 +-  ├─ random:index:RandomInteger  a               replace     [diff: ~seed]
 +   ├─ random:index:RandomInteger  d               replace     [diff: ~seed]      
 +-  ├─ random:index:RandomInteger  b               replace     [diff: ~seed]
 +-  └─ random:index:RandomInteger  c               replace     [diff: ~seed]
```

We've tried:
```
pulumi up -t 'urn:pulumi:scratch::pragma::random:index/randomInteger:RandomInteger::b' # makes changes to b
pulumi up -t 'urn:pulumi:scratch::pragma::random:index/randomInteger:RandomInteger::b' -t 'urn:pulumi:scratch::pragma::random:index/randomInteger:RandomInteger::c' # makes changes to b and c, as expected 
pulumi up -t 'urn:pulumi:scratch::pragma::random:index/randomInteger:RandomInteger::b' --target-dependents # makes changes to a, b, c and d
```

### Expected Behavior

Only `b` and `c` resources to be updated.

### Steps to reproduce

See code for stack above.

### Output of `pulumi about`

```
CLI
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME       VERSION
auth0      2.23.0
aws        5.41.0
buildkite  2.2.0
github     4.17.0
go         unknown
grafana    0.0.10
random     4.8.2

Host
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.20.5 darwin/arm64'

Current Stack: scratch

TYPE                                      URN
pulumi:pulumi:Stack                       urn:pulumi:scratch::pragma::pulumi:pulumi:Stack::pragma-scratch
pulumi:providers:random                   urn:pulumi:scratch::pragma::pulumi:providers:random::rand
random:index/randomInteger:RandomInteger  urn:pulumi:scratch::pragma::random:index/randomInteger:RandomInteger::a
random:index/randomInteger:RandomInteger  urn:pulumi:scratch::pragma::random:index/randomInteger:RandomInteger::d
random:index/randomInteger:RandomInteger  urn:pulumi:scratch::pragma::random:index/randomInteger:RandomInteger::b
random:index/randomInteger:RandomInteger  urn:pulumi:scratch::pragma::random:index/randomInteger:RandomInteger::c


Found no pending operations associated with scratch

Backend
Name           MAC-LPT-6320DD
URL            s3://infrogs-pulumi-prototype
User           jordan
Organizations

Dependencies:
NAME                                            VERSION
github.com/aws/aws-sdk-go-v2                    1.17.3
github.com/aws/aws-sdk-go-v2/config             1.18.2
github.com/aws/aws-sdk-go-v2/credentials        1.13.2
github.com/aws/aws-sdk-go-v2/service/ec2        1.72.0
github.com/aws/aws-sdk-go-v2/service/s3         1.30.0
github.com/aws/aws-sdk-go-v2/service/sts        1.17.4
github.com/aws/smithy-go                        1.13.5
github.com/blang/semver                         3.5.1+incompatible
github.com/lbrlabs/pulumi-grafana/sdk           0.0.10
github.com/pkg/errors                           0.9.1
github.com/pulumi/pulumi-auth0/sdk/v2           2.23.0
github.com/pulumi/pulumi-aws/sdk/v5             5.41.0
github.com/pulumi/pulumi-github/sdk/v4          4.17.0
github.com/pulumi/pulumi-random/sdk/v4          4.8.2
github.com/pulumi/pulumi/sdk/v3                 3.74.0
github.com/pulumiverse/pulumi-buildkite/sdk/v2  2.2.0
github.com/stretchr/testify                     1.8.2
golang.org/x/crypto                             0.10.0
golang.org/x/exp                                0.0.0-20230125214544-b3c2aaf6208d
gopkg.in/yaml.v3                                3.0.1
k8s.io/kops                                     1.25.2

Pulumi locates its logs in /var/folders/mj/9nfqzj_j1nn268qvqk7hv8fw0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I think this case of default providers is fixed by https://github.com/pulumi/pulumi/pull/13560. But you mentioned on slack you have uses case using explicit providers as well?

**Comment by chomey** [comment]
Sure. I haven't had a chance yet to test #13560 as it hasn't been released. With explicit providers, this exhibits the same behaviour:

```
	provider, err := random.NewProvider(ctx, "rand", &random.ProviderArgs{})
	if err != nil {
		return err
	}

	a, err := random.NewRandomInteger(ctx, "a", &random.RandomIntegerArgs{
		Max:  pulumi.Int(10000),
		Min:  pulumi.Int(1),
		Seed: pulumi.Sprintf("%s", time.Now().String()),
	}, pulumi.Provider(provider))
	if err != nil {
		return err
	}

	b, err := random.NewRandomInteger(ctx, "b", &random.RandomIntegerArgs{
		Max:  pulumi.Int(10000),
		Min:  pulumi.Int(1),
		Seed: pulumi.Sprintf("%s", time.Now().String(), a.Result),
	}, pulumi.Provider(provider))
	if err != nil {
		return err
	}

	_, err = random.NewRandomInteger(ctx, "c", &random.RandomIntegerArgs{
		Max:  pulumi.Int(10000),
		Min:  pulumi.Int(1),
		Seed: pulumi.Sprintf("%s%d", time.Now().String(), b.Result),
	}, pulumi.Provider(provider))
	if err != nil {
		return err
	}

	_, err = random.NewRandomInteger(ctx, "d", &random.RandomIntegerArgs{
		Max:  pulumi.Int(10000),
		Min:  pulumi.Int(1),
		Seed: pulumi.Sprintf("%s", time.Now().String()),
	}, pulumi.Provider(provider))
	if err != nil {
		return err
	}
```

**Comment by antdking** [comment]
Confirming still an issue in `3.78.1` when using explicit providers
