### ISSUE TITLE
Colour scheme is sometimes sub-optimal on common terminal themes

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi#1550]
I am using Solarized Dark in iTerm 2 on OSX, and on occasion (`pulumi refresh` for example) getting text rendered in the same colour as the background.

<img width="1130" alt="unhighlighted" src="https://user-images.githubusercontent.com/548524/41675575-a6ee93d6-7488-11e8-81a3-326594ba08ee.png">
<img width="1130" alt="highlighted" src="https://user-images.githubusercontent.com/548524/41675577-a8a0681c-7488-11e8-8d31-5723dc03e89f.png">

This may be a misconfiguration of my terminal, but I'm using the default iTerm theme so if it _is_ it's likely to be a common one. One option would be to disable colours, as per #1486, but since this is the only place I've so far seen this behaviour it might be good to modify the output to use another foreground colour.

**Comment by CyrusNajmabadi** [comment]
@jen20 Yikes!

THere are two things that can help mitigate this in the meantime in the latest builds of pulumi (which you probably won't get until our next release).

1. you can set an a NO_COLOR environment flag.  This will tell pulumi to not output colorized text. 
2. pass the --color=never flag to commands like 'pulumi update'

This will at least give you plain text so you can tell what's going on!

In the meantime, we'll have to see if there is some way to have colors, but also have them show up fine in any terminal.  Right now we're using a Go library for this purpose, and i don't know what facilities they have for helping out here.

**Comment by CyrusNajmabadi** [comment]
I'm going to move this out as there's a workaround one can apply currently.

**Comment by brandonbloom** [comment]
I actually think the color problem is higher priority than this ticket would suggest. Never mind merely popular themes, some stuff is almost unusable under the macOS default theme!

Here's some white on white text:

<img width="317" alt="screen shot 2018-09-15 at 10 04 21 am" src="https://user-images.githubusercontent.com/119164/45588760-e506c500-b8ce-11e8-8cd9-4a70f83e3515.png">

On my nice display, this is barely readable. On a crummy external monitor I occasionally use at the office, the contrast ratio is insufficient. This text is 100% invisible.

**Comment by CyrusNajmabadi** [comment]
@brandonbloom I was prioritizing based on the available workarounds.  Are they not currently sufficient for you?  If so, can you let me know why?  That would def help with prioritizing.  Thanks!

**Comment by brandonbloom** [comment]
I can disable color, but I'd rather not. I was merely pointing out that this problem doesn't just affect Solarized or similar custom themes, it also affects the default macOS configuration, which seems like it would raise the priority since it makes users need to use a workaround for an our of the box configuration.

**Comment by CyrusNajmabadi** [comment]
Interesting! @lukehoban @joeduffy @lukehoban are you seeing this on your Macs?

One of the main problems here that i can see is that we're effectively picking colors in the first place.  i.e. we do this:

```go
opts.Color.Colorize(colors.BrightWhite + message + colors.Reset)
```

Effectively, with that sort of an approach we'll always be bad in some color scheme depending on if the color we pick is close to whatever background it is for that command.

I'm not very familiar with this space. Does anyone know if there's a general 'go' library for picking text console colors in a more semantic fashion?  i.e. instead of specifying the color, you specify the intent, and proper colors are used based on the background. @pgavlin Do you have any ideas here?

**Comment by CyrusNajmabadi** [comment]
It may also just be that BrightWhite should just be removed/avoided entirely as it simply wouldn't be good choice for light-colored terminals.

**Comment by CyrusNajmabadi** [comment]
Similarly `SpecUnimportant = BrightBlack` looks to be problematic on some terminals.

**Comment by CyrusNajmabadi** [comment]
Note: i quick tried out getting rid of BrighBlack/White.  This produces the following for us:

![image](https://user-images.githubusercontent.com/4564579/45652046-30180800-ba88-11e8-9db1-a3a05713f0c5.png)

And: 

![image](https://user-images.githubusercontent.com/4564579/45652127-7d947500-ba88-11e8-80b0-5d1797cc9adc.png)

I think this would actually be a reasonable display to have.

**Comment by CyrusNajmabadi** [comment]
Here we are in solarized-light.  The yellow is not great.  But the whites have gotten much better:

![image](https://user-images.githubusercontent.com/4564579/45652328-1c20d600-ba89-11e8-8067-a57c9f0e17b5.png)

![image](https://user-images.githubusercontent.com/4564579/45652351-2c38b580-ba89-11e8-8c05-3a444e01e340.png)

**Comment by CyrusNajmabadi** [comment]
Solarized dark:

![image](https://user-images.githubusercontent.com/4564579/45652413-66a25280-ba89-11e8-911b-a88545176d51.png)

![image](https://user-images.githubusercontent.com/4564579/45652437-76ba3200-ba89-11e8-9e4b-72b250a8e972.png)

**Comment by CyrusNajmabadi** [comment]
I'm going to open a PR with this change.  It would be helpful if someone on Mac could show how it looks.

**Comment by CyrusNajmabadi** [comment]
@jen20 @brandonbloom Do you think you would be ok with the above?

**Comment by CyrusNajmabadi** [comment]
With cyan as our prompt color:

![image](https://user-images.githubusercontent.com/4564579/45654295-eb906a80-ba8f-11e8-9a04-a6f4a59434a8.png)

![image](https://user-images.githubusercontent.com/4564579/45654316-fd720d80-ba8f-11e8-8a54-5e084d2cad72.png)

![image](https://user-images.githubusercontent.com/4564579/45654330-09f66600-ba90-11e8-8e0f-9d2ac01b16b1.png)

**Comment by brandonbloom** [comment]
Did you test on a pure white background terminal too?

**Comment by CyrusNajmabadi** [comment]
nope!  i'll ttry that now.

**Comment by CyrusNajmabadi** [comment]
Pure white BG:

![image](https://user-images.githubusercontent.com/4564579/45655930-8476b400-ba97-11e8-88f0-eb8c87f4a4a7.png)

![image](https://user-images.githubusercontent.com/4564579/45655999-e2a39700-ba97-11e8-9da3-b09e05ac3626.png)

As with the light BG, the yellow is not great.  But the problem is not as severe as when we started this convo :)

**Comment by CyrusNajmabadi** [comment]
Here's an approach where we orange for changes and magenta for replaces:

![image](https://user-images.githubusercontent.com/4564579/45664652-d3d1da00-bac1-11e8-8024-b59fb9bf6335.png)

![image](https://user-images.githubusercontent.com/4564579/45664664-e21ff600-bac1-11e8-8c2d-5fdd1154cea6.png)

![image](https://user-images.githubusercontent.com/4564579/45664681-f663f300-bac1-11e8-9bb0-5c957b3fcb3c.png)

![image](https://user-images.githubusercontent.com/4564579/45664695-0e3b7700-bac2-11e8-9d2a-c6c54752634d.png)

I actually think this is pretty good.  And it avoids the bright-yellow/white/black problem entirely.  What do you think @lukehoban @joeduffy

**Comment by CyrusNajmabadi** [comment]
No one is protesting the new colors.  So i'm going to go ahead with them :)  I expect i'll hear about any unhappiness soon :)

**Comment by jen20** [comment]
They look good to me! I've been running with no colour for a while, looking forward to this!

**Comment by brandonbloom** [comment]
Thanks for taking some action here, much appreciated!

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/pulumi/pulumi/pull/1951  Thanks or your help guys.  Much appreciated!

**Comment by paymog** [comment]
I recently (yesterday) installed pulumi with brew but it seems I'm still seeing the old color schemes. How can I get a version of pulumi with this fix?

**Comment by CyrusNajmabadi** [comment]
@paymog The fix will hopefully be in our next upcoming release.  @ellismg May have more details on the specific dates for that.  Thanks!

**Comment by ellismg** [comment]
We plan to do an all up release in the middle of next week, and the version in Brew will be updated at that time.
