### ISSUE TITLE
Wrong node_modules dependency included in package for await import

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1567]
From @codymccodeface on slack:

> I think I worked out whats happening. If I put this within my handler function `const jwt = await import('jsonwebtoken');` it actually packages the `@types/jsonwebtoken` module rather than the actual `jsonwebtoken` module. Note that `@types/jsonwebtoken` is in my devDependencies

> So removing `@types/jsonwebtoken` and changing the line to `const jwt = require('jsonwebtoken');` fixed the build but obviously the library becomes an `any` which is a bit annoying but I can deal with it.

We addresses a similar/same case in https://github.com/pulumi/pulumi-aws/pull/230, so will need to look into why that fix didn’t work here.

**Comment by joeduffy** [comment]
@CyrusNajmabadi Is this still an issue, or have we fixed this with the various closure/module serialization changes we've made over the past couple months?

**Comment by rlgod** [comment]
@joeduffy I'm going to do some re-testing of the stuff I wrote back then to see if it's working as intended now. I'll get back to you ASAP.

**Comment by CyrusNajmabadi** [comment]
@rlgod I would definitely appreciate that.  This should now work as expected.  We don't actually look at your code anymore to determine this.  instead we use the package.json (and, specifically, the 'dependencies' object in it) as the authoritative source of truth.  So this should just work properly.  Let us know if it doesn't!

**Comment by rlgod** [comment]
Looks like it might be a bit better but I'm still getting issues because pulumi can't serialize a native code function.
```
    '(ev, ctx, cb) => { let body; ...': api.js(234,106): captured
      variable 'route' which indirectly referenced
        '(req, res, next) => __awaiter(this,  ...': Authorizer.function.js(37,15): which captured
          module './node_modules\\jsonwebtoken\\index.js' which indirectly referenced
            function '<anonymous>': verify.js(8,26): which captured
              module './node_modules\\jsonwebtoken\\decode.js' which indirectly referenced
                function '<anonymous>': decode.js(3,26): which captured
                  module './node_modules\\jws\\index.js' which indirectly referenced
                    function 'jwsDecode': verify-stream.js(57,18): which referenced
                      function 'isValidJws': verify-stream.js(40,19): which captured
                        variable 'JWS_REGEX' which indirectly referenced
                          function 'test': which could not be serialized because
                            it was a native code function.
```

**Comment by CyrusNajmabadi** [comment]
Are you on windows?  This looks like the following issue that we fixed here: https://github.com/pulumi/pulumi/commit/43674dcef54fb85a359526f8a11dca4bb6a95d94

Also, can you show the code you have?  A link or gist would be great.  Thanks!

**Comment by rlgod** [comment]
It's possible. I don't have any code I can share right now. Perhaps I'll investigate further at some point and open a new issue if it's still a problem. This code was written 4 months ago and I've just updated pulumi and the pulumi libraries to the latest version to test it. I was doing some experimenting using typescript decorators to inject node package dependencies into a TS class so it may be something to do with that.

**Comment by CyrusNajmabadi** [comment]
@rlgod We've definitely changed a bunch of things around closure-serialization as well as node_modules capturing.  We think the current design should work really well now, with very little 'gotcha's.  If you are running into a problem when using a more current version of pulumi, let me know.  It may either be bugs we need to take care of asap, or it might require some code changes in your code (ideally to make it all more idiomatically js/ts code, instead of having to contort more to how pulumi used to require things).

For now, i'm going to close this out as i think the original issue has been resolved.  Thanks!
