### ISSUE TITLE
Mocks don't work with parameterised SDKs

### ISSUE THREAD

**Issue by stooj** [pulumi/pulumi#19688]
### What happened?

I'm having trouble mocking some resources of a Terraform-bridged provider. We've created a Pulumi provider out of [terraform-provider-couchbase-capella](https://github.com/couchbasecloud/terraform-provider-couchbase-capella), published in our private NPM registry and created a project that uses this provider.

I'm trying to write a unit test for a new resource but the unit test times out. When I check by throwing errors directly in the mock, it doesn't look like the `newResource` mock gets called.

The error is lost, but after attaching a debugger we found:

> Error: The Pulumi CLI does not support parameterization. Please update the Pulumi CLI

### Example

If I set the mock like this:

```typescript
pulumi.runtime.setMocks(
  {
    newResource: function (args: pulumi.runtime.MockResourceArgs): {
      id: string;
      state: any;
    } {
      console.log("NEW RESOURCE");
      const err = new Error("NEW RESOURCE - THROW");
    },
    call: function (args: pulumi.runtime.MockCallArgs) {
      console.log("In call function");
      throw new Error("Calling error");
      return args.inputs;
    },
  },
  "project",
  "stack",
  false,
);
```

`npm test` prints this:

```
  MyNewService
NEW RESOURCE
    ✔ should create MyNewService
```

### Output of `pulumi about`

```
CLI
Version      3.173.0
Go Version   go1.24.3
Go Compiler  gc

Plugins
KIND      NAME                VERSION
language  nodejs              3.173.0
resource  terraform-provider  0.10.0
resource  terraform-provider  0.10.0

Host
OS       nixos
Version  25.05 (Warbler)
Arch     x86_64

This project is written in nodejs: executable='/nix/store/wfxq6w9bkp5dcfr8yb6789b0w7128gnb-nodejs-20.18.1/bin/node' version='v20.18.1'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/stooj
User           stooj
Organizations  stooj, higara, team-ce, team-ce-enterprise, team-ce-team, demo, higara-free
Token type     personal

Dependencies:
NAME                       VERSION
chai                       5.2.0
mocha                      11.5.0
tsx                        4.19.4
@pulumi/couchbase-capella  1.4.1
@pulumi/pulumi             3.173.0
@types/mocha               10.0.10
@types/node                10.17.60
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
While fixing this we should probably look at making [transforms be marked as supported](https://github.com/pulumi/pulumi/issues/17090) as well (even if they don't do anything).

**Comment by Frassle** [comment]
We still need to fix dotnet and java.

**Comment by lunaris** [comment]
I think all languages now have SDK fixes merged; when this week's release goes out we can close this.

**Comment by Frassle** [comment]
I'm just writing up a sanity test for dotnet, but yes everything seems fixed.

**Comment by BarboraAni** [comment]
Hi, the fix from #19722 doesn't seem to work for Python.

```bash
CLI
Version      3.229.0
Go Version   go1.26.1
Go Compiler  gc

Plugins
KIND      NAME                VERSION
resource  netbox              0.1.5
language  python              3.229.0
resource  terraform-provider  1.0.2

Host
OS       darwin
Version  26.1
Arch     arm64

This project is written in python: executable='<REDACTED>' version='3.13.12' typechecker='None' toolchain='Poetry' toolchainVersion='2.3.2'

Backend
Name           <REDACTED>
URL            <REDACTED>
User           <REDACTED>
Organizations
Token type     personal

Dependencies:
NAME                       VERSION
bandit                     1.9.4
black                      25.12.0
confuse                    2.2.0
flake8                     7.3.0
flake8-annotations         3.2.0
flake8-pyproject           1.2.4
isort                      6.1.0
mypy                       1.19.1
pulumi                     3.226.0
pulumi-prefect             2.92.9
pydantic                   2.12.5
pydantic-settings          2.13.1
pytest                     9.0.2
pytest-cov                 7.0.0
pytest-subprocess          1.5.3
pytest-xdist               3.8.0
pyyaml                     6.0.3
tox                        4.49.1
```

```python
# conftest.py
import pulumi
import pytest

class PulumiMocks(pulumi.runtime.Mocks):
    def __init__(self) -> None:
        self.resources = []
        super().__init__()

    def new_resource(self, args: pulumi.runtime.MockResourceArgs):
        self.resources.append(
            {
                "type": args.typ,
                "name": args.name,
                "inputs": args.inputs,
                "provider": args.provider,
            }
        )
        return [args.name + "_id", args.inputs]

    def call(self, args: pulumi.runtime.MockCallArgs):
        return {}

@pytest.fixture
def pulumi_mocks():
    mocks = PulumiMocks()
    pulumi.runtime.set_mocks(mocks)
    return mocks
```

```python
# test_parameterized.py
import pulumi
import pulumi_prefect as prefect

@pulumi.runtime.test
def test_prefect_variable(pulumi_mocks):
    variable = prefect.Variable("my-variable", value="test-value")

    def check(args):
        assert pulumi_mocks.resources == [
            {
                "type": "prefect:index/variable:Variable",
                "name": "my-variable",
                "inputs": {"value": "test-value"},
                "provider": "",
            }
        ]

    return variable.id.apply(check)
```

Still fails with:

```
Exception: The Pulumi CLI does not support parameterization. Please update the Pulumi CLI.
```
