### ISSUE TITLE
stack hangs when an error occurs during stack.up operations (with pulumi automation api)

### ISSUE THREAD

**Issue by skarltjr** [pulumi/pulumi#20263]
- If there's anything I've done wrong, I'd appreciate it if you could let me know

### What happened?

env
```
"@pulumi/aws": "^7.3.1",
"@pulumi/pulumi": "^3.188.0",
Node.js v23.5.0
```

slack
- https://pulumi-community.slack.com/archives/CJ909TL6P/p1754891037232349

problem
```
"I'm currently using Pulumi automation API and componentResource.
I've encountered an issue where the stack hangs when problems occur during stack.up operations.

In the code above, when an IAM role already exists, a 409 entity already exists error occurs and causes the stack to hang.

I'm not looking for workarounds like import.

I want to understand why the stack hangs and doesn't reach the summary event when issues occur during stack operations.
```

### Example

below is the code for repro
```
import { LocalWorkspace, Stack } from '@pulumi/pulumi/automation/index.js';
import * as pulumi from '@pulumi/pulumi';
import * as aws from '@pulumi/aws';


class ECSTaskRoleComponent extends pulumi.ComponentResource {
  public taskRole: aws.iam.Role;
  public taskRolePolicy: aws.iam.RolePolicy;

  constructor(name: string, opts?: pulumi.ComponentResourceOptions) {
    super('custom:aws:ECSTaskRole', name, {}, opts);

    this.taskRole = new aws.iam.Role(`${name}-task-role`, {
      name: `${name}-task-role`,
      assumeRolePolicy: JSON.stringify({
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Principal: {
              Service: 'ecs-tasks.amazonaws.com',
            },
            Action: 'sts:AssumeRole',
          },
        ],
      }),
      tags: {
        Name: `${name}-task-role`,
        Environment: 'test',
      },
    }, { parent: this });

    this.taskRolePolicy = new aws.iam.RolePolicy(`${name}-task-role-policy`, {
      name: `${name}-task-role-policy`,
      role: this.taskRole.id,
      policy: JSON.stringify({
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              's3:GetObject',
              's3:PutObject',
              's3:DeleteObject',
              's3:ListBucket',
            ],
            Resource: [
              'arn:aws:s3:::test-bucket',
              'arn:aws:s3:::test-bucket/*',
            ],
          },
          {
            Effect: 'Allow',
            Action: [
              'logs:CreateLogGroup',
              'logs:CreateLogStream',
              'logs:PutLogEvents',
            ],
            Resource: '*',
          },
        ],
      }),
    }, { parent: this });
    this.registerOutputs({
      taskRoleArn: this.taskRole.arn,
      taskRoleName: this.taskRole.name,
      taskRolePolicyName: this.taskRolePolicy.name,
    });
  }
}
function createSimplePulumiProgram() {
  return async () => {
    const ecsTaskRole = new ECSTaskRoleComponent('kidol-zz-service');

    // 출력
    return {
      taskRoleArn: ecsTaskRole.taskRole.arn,
      taskRoleName: ecsTaskRole.taskRole.name,
      taskRolePolicyName: ecsTaskRole.taskRolePolicy.name,
    };
  };
}
async function testPulumiAutomation() {
  
  const stackName = 'test~';
  const projectName = 'test~';
  const backendUrl = 's3://test~';
  
  let stack: Stack | undefined;
  
  try {
    console.log(`Creating stack: ${stackName}`);
    console.log(`Project name: ${projectName}`);
    console.log(`Backend URL: ${backendUrl}`);
    
    stack = await LocalWorkspace.createOrSelectStack(
      {
        stackName,
        projectName,
        program: createSimplePulumiProgram(),
      },
      {
        projectSettings: {
          name: projectName,
          runtime: 'nodejs',
          backend: {
            url: backendUrl,
          },
        },
        envVars: {
          PULUMI_CONFIG_PASSPHRASE: 'dev-passphrase',
        },
      },
    );

    console.log(`Stack created: ${stack.name}`);
    console.log('Starting stack up operation...');

    const upPromise = stack.up({
      refresh: true,
      showSecrets: true,
      onOutput: console.log,
    });

    await upPromise;
    console.log('Stack up completed successfully!');

  } catch (error) {
    console.error(`Error: ${error instanceof Error ? error.message : String(error)}`);
  }
}
testPulumiAutomation().catch((error) => {
  console.error(`Error: ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
});
```

- output log
```
node dist/index.js
Creating stack: ~~
Project name: ~~~
Backend URL: ~~~
Stack created: ~~~
Starting stack up operation...
Updating (aws-test-corp-kint5-ap-northeast-2-dev-ECS-kidol-zz-service):



 ~  pulumi:pulumi:Stack aws-test-corp-kint5-ap-northeast-2-dev-ECS-kidol-zz-service-aws-test-corp-kint5-ap-northeast-2-dev-ECS-kidol-zz-service refreshing (0s) 
 ~  custom:aws:ECSTaskRole kidol-zz-service refreshing (0s) 

 ~  custom:aws:ECSTaskRole kidol-zz-service refresh (0.00s) 
 ~  pulumi:pulumi:Stack aws-test-corp-kint5-ap-northeast-2-dev-ECS-kidol-zz-service-aws-test-corp-kint5-ap-northeast-2-dev-ECS-kidol-zz-service refreshing (0s) 

    pulumi:pulumi:Stack aws-test-corp-kint5-ap-northeast-2-dev-ECS-kidol-zz-service-aws-test-corp-kint5-ap-northeast-2-dev-ECS-kidol-zz-service running 

    custom:aws:ECSTaskRole kidol-zz-service  

@ updating....
.

 +  aws:iam:Role kidol-zz-service-task-role creating (0s) 

@ updating....

 +  aws:iam:Role kidol-zz-service-task-role creating (0s) error:   sdk-v2/provider2.go:572: sdk.helper_schema: creating IAM Role (kidol-zz-service-task-role): operation error IAM: CreateRole, https response error StatusCode: 409, RequestID: 9876e2e1-0133-4f77-88a8-8bae786deef8, EntityAlreadyExists: Role with name kidol-zz-service-task-role already exists.: provider=aws@7.3.1

 +  aws:iam:Role kidol-zz-service-task-role creating (0s) error: 1 error occurred:

 +  aws:iam:Role kidol-zz-service-task-role **creating failed** error: 1 error occurred:

    pulumi:pulumi:Stack aws-test-corp-kint5-ap-northeast-2-dev-ECS-kidol-zz-service-aws-test-corp-kint5-ap-northeast-2-dev-ECS-kidol-zz-service running error: update failed

@ updating....
.
.
.
.
.
.
```

### Output of `pulumi about`

a18144@18144ui-noteubug worker % pulumi about
CLI          
Version      3.181.0
Go Version   go1.24.4
Go Compiler  gc

Host     
OS       darwin
Version  14.6.1
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by skarltjr** [comment]
It seems to be resolved after making the following changes.
I think refresh is the main factor here.

1. Changed local Pulumi CLI version to 3.188.0
package.json == "@pulumi/pulumi": "^3.188.0",
local pulumi cli version == 3.181.0

2. Removed the refresh option"

**Comment by danialhardi90** [comment]
Hi skarltjr,

I'm asking(using my method asking) your issue to AI. They give this;

"The problem isn’t in the ECS service or the task definition — it’s in the IAM Role that serves as the base for ECSTaskRole.

The root cause is that Pulumi’s state doesn’t know the role already exists (whether it was created manually or by another stack)."

**Comment by julienp** [comment]
> It seems to be resolved after making the following changes. I think refresh is the main factor here.
> 
> 1. Changed local Pulumi CLI version to 3.188.0
>    package.json == "@pulumi/pulumi": "^3.188.0",
>    local pulumi cli version == 3.181.0
> 2. Removed the refresh option"

Would it be possible to check if still works with refresh enabled and Pulumi CLI & `@pulumi/pulumi` both at 3.188.0? There were some bugs that look similar to this in recent versions that have been fixed.

**Comment by danialhardi90** [comment]
The error output contains repetitions that can be considered spammy, so aggregation and deduplication can be improved.

**Comment by skarltjr** [comment]
@julienp 😄 thank you!

The issue still occurs even after changing to the version you mentioned.
This seems to be a problem with --refresh --run-program.
The issue doesn't occur when running refresh() and up() separately.
- You might want to refer to the slack thread as well!"

**Comment by Frassle** [comment]
Looks like another --refresh --run-program issue. We're looking into a few of them at the moment.
