### ISSUE TITLE
Snapshot integrity error updating k8s external secret custom resource API version

### ISSUE THREAD

**Issue by acheng52** [pulumi/pulumi#20535]
### What happened?

We're trying to update https://www.pulumi.com/registry/packages/kubernetes/api-docs/apiextensions/customresource/#api_version_python for some external secret resources from `external-secrets.io/v1beta1` to `external-secrets.io/v1`. A pulumi preview for the stack in our CI/CD pipeline seems to result in a snapshot integrity error. Locally run it seems to work fine.

### Example

Pulumi preview output
```
================================================================================
Go Version:        go1.25.0
Go Compiler:       gc
Architecture:      amd64
Operating System:  linux
Pulumi Version:    v3.192.0
Command:           pulumi refresh --run-program --cwd src/aws/eks/observability -s ipd-eks-apse2-observability --skip-preview --color always --yes
Error:             writing snapshot: failed to save snapshot: .pulumi/stacks/ipd-eks-apse2-observability.json: snapshot integrity failure; it was already written, but is invalid (backup available at .pulumi/stacks/ipd-eks-apse2-observability.json.bak): resource urn:pulumi:ipd-eks-apse2-observability::itplat::kubernetes:helm.sh/v3:Chart::osquery's dependency urn:pulumi:ipd-eks-apse2-observability::itplat::kubernetes:external-secrets.io/v1:ExternalSecret::apse2-osquery-secret-external-secret refers to missing resource
Stack Trace:
goroutine 97 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
[github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf](http://github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf)({0x2dff520?, 0x86?}, {0xc00257bd10?, 0x86?, 0x2a05120?})
	[github.com/pulumi/pulumi/pkg/v3/resource/deploy/snapshot.go:631](http://github.com/pulumi/pulumi/pkg/v3/resource/deploy/snapshot.go:631) +0x34
[github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot](http://github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot)).VerifyIntegrity(0xc0022a20a0)
	[github.com/pulumi/pulumi/pkg/v3/resource/deploy/snapshot.go:507](http://github.com/pulumi/pulumi/pkg/v3/resource/deploy/snapshot.go:507) +0x11e9
[github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend](http://github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend)).saveStack(0xc0018dde60, {0x352cae0, 0x4cdd720}, 0xc00240f080, 0xc0022a20a0)
	[github.com/pulumi/pulumi/pkg/v3/backend/diy/state.go:277](http://github.com/pulumi/pulumi/pkg/v3/backend/diy/state.go:277) +0x13d
[github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diySnapshotPersister](http://github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diySnapshotPersister)).Save(0xc00004e0b0?, 0x1b?)
	[github.com/pulumi/pulumi/pkg/v3/backend/diy/snapshot.go:35](http://github.com/pulumi/pulumi/pkg/v3/backend/diy/snapshot.go:35) +0x2b
[github.com/pulumi/pulumi/pkg/v3/backend.(*SnapshotManager](http://github.com/pulumi/pulumi/pkg/v3/backend.(*SnapshotManager)).saveSnapshot(0xc001d4c000)
	[github.com/pulumi/pulumi/pkg/v3/backend/snapshot.go:747](http://github.com/pulumi/pulumi/pkg/v3/backend/snapshot.go:747) +0x1ae
[github.com/pulumi/pulumi/pkg/v3/backend.(*SnapshotManager](http://github.com/pulumi/pulumi/pkg/v3/backend.(*SnapshotManager)).defaultServiceLoop(0xc001d4c000, 0xc0020622a0, 0xc002062380)
	[github.com/pulumi/pulumi/pkg/v3/backend/snapshot.go:783](http://github.com/pulumi/pulumi/pkg/v3/backend/snapshot.go:783) +0x139
created by [github.com/pulumi/pulumi/pkg/v3/backend.NewSnapshotManager](http://github.com/pulumi/pulumi/pkg/v3/backend.NewSnapshotManager) in goroutine 1
	[github.com/pulumi/pulumi/pkg/v3/backend/snapshot.go:835](http://github.com/pulumi/pulumi/pkg/v3/backend/snapshot.go:835) +0x270
```

### Output of `pulumi about`

+ pulumi about -C src/aws/eks/observability -s ipd-eks-apse2-observability
CLI          
Version      3.192.0
Go Version   go1.25.0
Go Compiler  gc
warning: Failed to get information about the current stack: snapshot integrity failure; refusing to use it: resource urn:pulumi:ipd-eks-apse2-observability::itplat::kubernetes:helm.sh/v3:Chart::osquery's dependency urn:pulumi:ipd-eks-apse2-observability::itplat::kubernetes:external-secrets.io/v1:ExternalSecret::apse2-osquery-secret-external-secret refers to missing resource
Plugins
KIND      NAME        VERSION
resource  aws         7.0.0
resource  aws-native  1.10.0
resource  command     1.0.1
resource  kubernetes  4.18.3
resource  postgresql  3.11.1
language  python      3.192.0
resource  random      4.16.2
Host     
OS       debian
Version  11.11
Arch     x86_64
This project is written in python: executable='/usr/local/bin/python3' version='3.13.6'
Backend        
Name           7237c440-9856-4a16-8b5d-d54f308cb10e-998h6
URL            s3://<redacted>
User           root
Organizations  
Token type     personal
Dependencies:
NAME               VERSION
backoff            2.2.1
black              24.10.0
boto3              1.34.118
coloredlogs        15.0.1
GitPython          3.1.41
Jinja2             3.1.2
kubernetes         27.2.0
mergedeep          1.3.4
pre_commit         4.0.1
pulumi_aws         7.0.0
pulumi_aws_native  1.10.0
pulumi_command     1.0.1
pulumi_kubernetes  4.18.3
pulumi_postgresql  3.11.1
pulumi_random      4.16.2
pyhumps            3.7.2
setuptools         80.9.0
Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Can you update your cli to latest and try again? There were some issues with snapshot integrity that have been fixed recently, this might be one of them. Else it's likely similar to other refresh --run-program issues that are currently being worked on.

**Comment by tgummerer** [comment]
While we're looking into this, you should be able to repair the stack by running `pulumi repair` on the stack, and all further operations should succeed again.

**Comment by acheng52** [comment]
Thanks, unfortunately I still get the same error on the latest CLI version (I made sure to pulumi repair the stack beforehand):
```
================================================================================
Go Version:        go1.25.1
Go Compiler:       gc
Architecture:      amd64
Operating System:  linux
Pulumi Version:    v3.197.0
Command:           pulumi refresh --run-program --cwd src/aws/eks/observability -s ipd-eks-apse2-observability --skip-preview --color always --yes
Error:             writing snapshot: failed to save snapshot: .pulumi/stacks/ipd-eks-apse2-observability.json: snapshot integrity failure; it was already written, but is invalid (backup available at .pulumi/stacks/ipd-eks-apse2-observability.json.bak): resource urn:pulumi:ipd-eks-apse2-observability::itplat::kubernetes:helm.sh/v3:Chart::osquery's dependency urn:pulumi:ipd-eks-apse2-observability::itplat::kubernetes:external-secrets.io/v1:ExternalSecret::apse2-osquery-secret-external-secret refers to missing resource
Stack Trace:
goroutine 48 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
[github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf](http://github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf)({0x2e4172e?, 0x86?}, {0xc001171d10?, 0x86?, 0x2a41d00?})
	[github.com/pulumi/pulumi/pkg/v3/resource/deploy/snapshot.go:718](http://github.com/pulumi/pulumi/pkg/v3/resource/deploy/snapshot.go:718) +0x34
[github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot](http://github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot)).VerifyIntegrity(0xc0009fe0a0)
	[github.com/pulumi/pulumi/pkg/v3/resource/deploy/snapshot.go:594](http://github.com/pulumi/pulumi/pkg/v3/resource/deploy/snapshot.go:594) +0x11e9
[github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend](http://github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend)).saveStack(0xc00161c900, {0x3576b60, 0x4d480e0}, 0xc00247dd80, 0xc0009fe0a0)
	[github.com/pulumi/pulumi/pkg/v3/backend/diy/state.go:277](http://github.com/pulumi/pulumi/pkg/v3/backend/diy/state.go:277) +0x13d
[github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diySnapshotPersister](http://github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diySnapshotPersister)).Save(0xc00004e0b0?, 0x1b?)
	[github.com/pulumi/pulumi/pkg/v3/backend/diy/snapshot.go:35](http://github.com/pulumi/pulumi/pkg/v3/backend/diy/snapshot.go:35) +0x2b
[github.com/pulumi/pulumi/pkg/v3/backend.(*SnapshotManager](http://github.com/pulumi/pulumi/pkg/v3/backend.(*SnapshotManager)).saveSnapshot(0xc0009794d0)
	[github.com/pulumi/pulumi/pkg/v3/backend/snapshot.go:755](http://github.com/pulumi/pulumi/pkg/v3/backend/snapshot.go:755) +0x1ae
[github.com/pulumi/pulumi/pkg/v3/backend.(*SnapshotManager](http://github.com/pulumi/pulumi/pkg/v3/backend.(*SnapshotManager)).defaultServiceLoop(0xc0009794d0, 0xc001ace0e0, 0xc001ace2a0)
	[github.com/pulumi/pulumi/pkg/v3/backend/snapshot.go:791](http://github.com/pulumi/pulumi/pkg/v3/backend/snapshot.go:791) +0x139
created by [github.com/pulumi/pulumi/pkg/v3/backend.NewSnapshotManager](http://github.com/pulumi/pulumi/pkg/v3/backend.NewSnapshotManager) in goroutine 1
	[github.com/pulumi/pulumi/pkg/v3/backend/snapshot.go:843](http://github.com/pulumi/pulumi/pkg/v3/backend/snapshot.go:843) +0x270
```

I can actually reproduce this locally too (I think I was running a different command yesterday). In case its helpful, dropping `--run-program` makes the refresh work.

**Comment by tgummerer** [comment]
Thanks for the info!  I *think* this will be fixed in the next releases, https://github.com/pulumi/pulumi/pull/20551 and https://github.com/pulumi/pulumi/issues/20215 should fix the issue.  I'm not 100% sure of that, because while I could reproduce the same error, there might be other mechanisms of how we can get to it, that we haven't discovered yet.  If you have a small reproduction example that we can use to test that would be very helpful, otherwise hopefully with the next release of pulumi/pulumi you can double check that this will be fixed.

**Comment by acheng52** [comment]
Thanks @tgummerer that sounds promising. I've actually just encountered the problem on a different stack. I'll paste the logs + a bit of our code:

```
Go Version:        go1.25.1
Go Compiler:       gc
Architecture:      arm64
Operating System:  darwin

Pulumi Version:    v3.197.0
Command:           pulumi refresh --run-program --cwd src/aws/s3 -s ipd-s3-all --skip-preview --color always --yes
Error:             writing snapshot: failed to save snapshot: .pulumi/stacks/ipd-s3-all.json: snapshot integrity failure; it was already written, but is invalid (backup available at .pulumi/stacks/ipd-s3-all.json.bak): resource urn:pulumi:ipd-s3-all::itplat::aws:s3/bucketAcl:BucketAcl::atl-tableau-629205377521-acl's dependency urn:pulumi:ipd-s3-all::itplat::aws:s3/bucketOwnershipControls:BucketOwnershipControls::atl-tableau-629205377521-bucket-ownership-controls refers to missing resource

Stack Trace:

goroutine 131 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.25.1/libexec/src/runtime/debug/stack.go:26 +0x64
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x10455d6e9?, 0x89?}, {0x14002c9fcf0?, 0x89?, 0x1050e2e00?})
        /private/tmp/pulumi-20250917-4915-nxd13h/pkg/resource/deploy/snapshot.go:718 +0x30
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0x1400398ed20)
        /private/tmp/pulumi-20250917-4915-nxd13h/pkg/resource/deploy/snapshot.go:594 +0xd54
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diyBackend).saveStack(0x140021a8750, {0x105420340, 0x106b87560}, 0x14000ec0dc0, 0x1400398ed20)
        /private/tmp/pulumi-20250917-4915-nxd13h/pkg/backend/diy/state.go:277 +0x100
github.com/pulumi/pulumi/pkg/v3/backend/diy.(*diySnapshotPersister).Save(0x1400004e0b0?, 0x1039b0610?)
        /private/tmp/pulumi-20250917-4915-nxd13h/pkg/backend/diy/snapshot.go:35 +0x2c
github.com/pulumi/pulumi/pkg/v3/backend.(*SnapshotManager).saveSnapshot(0x1400213aea0)
        /private/tmp/pulumi-20250917-4915-nxd13h/pkg/backend/snapshot.go:755 +0x178
github.com/pulumi/pulumi/pkg/v3/backend.(*SnapshotManager).defaultServiceLoop(0x1400213aea0, 0x14001ac6070, 0x14001ac6150)
        /private/tmp/pulumi-20250917-4915-nxd13h/pkg/backend/snapshot.go:791 +0x108
created by github.com/pulumi/pulumi/pkg/v3/backend.NewSnapshotManager in goroutine 1
        /private/tmp/pulumi-20250917-4915-nxd13h/pkg/backend/snapshot.go:843 +0x218
```

```
...
    bucket = aws.s3.Bucket(name, region=definition['region'], **definition['properties'])

    if ownership_controls:
        bucket_ownership_controls = aws.s3.BucketOwnershipControls(f'{name}-bucket-ownership-controls', bucket=bucket.id, region=definition['region'], **ownership_controls)
    if acl:
        bucket_acl = aws.s3.BucketAcl(f'{name}-acl', bucket=bucket.id, region=definition['region'], acl=acl, opts=pulumi.ResourceOptions(depends_on=[bucket_ownership_controls]))
...
```

**Comment by tgummerer** [comment]
Thanks for the code sample, this is helpful!  I'm guessing `bucket_acl` is an already existing resource, and `bucket_ownership_controls` was added to the program but not `up`ed yet.  And then the refresh does a skipped create for `bucket_ownership_controls` during the refresh, and adds it as a dependency for `bucket_acl`.  But as it's a skipped create it doesn't really exist, and then writing `bucket_acl` with the dependency to the snapshot fails.  

We should be releasing Pulumi 3.198.0 today, that includes the fix.  If it still happens when running `pulumi refresh --run-program` with that version, after repairing the stack, please feel free to reopen, and we can investigate more, but I'm somewhat confident that this fixes the issue you're experiencing.  Sorry about the trouble here!

**Comment by acheng52** [comment]
No worries, can confirm it looks like --run-program refreshes work fine for us on 3.198.0 now
