### ISSUE TITLE
Support Node 11

### ISSUE THREAD

**Issue by mehzer** [pulumi/pulumi#2096]

**Comment by swgillespie** [comment]
With https://github.com/pulumi/pulumi/pull/2098 we should be able to do everything with Node 11 except for function serialization.

**Comment by CyrusNajmabadi** [comment]
Ok.  So here are the results of investigating things:

The following functions that we use have been removed: FunctionGetScript, FunctionGetScriptSourcePosition, GetFunctionScopeCount and GetFunctionScopeDetails.  The first two are more minor and are needed to just get the position of a function so we can report error messages at good locations.  If we can't get those, we can always print no location.  While not great, we also print out the first 5 lines of a function, as well as the stack it was called from.  So it's usually not too hard to find it.   The latter two methods are a serious issue for us as they are how we lookup free variables captured by functions.  

In order to deal with this, we need to use hte node '[inspector](https://nodejs.org/api/inspector.html)' API.  From the inspector (which is supported from node 10 onwards).  Importantly, from 10 onwards it can be used *without* an attached debugger AFAICT.

From the 'inspector' API, it's possible to get an instance of the [Runtime protocol](https://chromedevtools.github.io/devtools-protocol/1-3/Runtime).  This is the API that allows one to query the runtime to get information about Functions/Objects/etc.  The cons here are that this API never gives you back the real JS obejcts.  Instead, you get back 'runtime handles' to objects that you then call more protocol methods on to get more information.  Relevant helpers are functions like [Runtime.getProperties](https://chromedevtools.github.io/devtools-protocol/1-3/Runtime#method-getProperties).

Note: in order to start using these we need to be able to go from a real JS function instance that we were asked to serialize to the "Runtime Id" for it.  This is tricky, but doable.  Specifically, we just need to assign this function to a well known place (like "global.funcToSerialize"), then execute: `Runtime.evaluate({
expression: "funcToSerialize" }` to actually get start introspecting.

I spelunked through V8, and it looks like they do include information we need in the properties you get back from a function: https://cs.chromium.org/chromium/src/v8/src/inspector/v8-debugger.cc?rcl=381ff28a8e9c3264cc9914723863903f07a4bc87&l=751

Specifically, they include 'internalProperties' like `[[scopes]]` which should contain what we need.  The downside here is that i think this is still undocumented.  So it may still be removed in the future.  However, i think we should at least be safe for the 11.0 timeframe.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/pulumi/pulumi/pull/2101

**Comment by wstrange** [comment]
I think I am still seeing this error. On my mac, node 11, I get:

```
error: Running program '/Users/warren.strange/tmp/forgeops/tmp/gke' failed with an unhandled exception:
    error: SyntaxError: FunctionGetScript is not defined
        at new Function (<anonymous>)
        at Object.<anonymous> (/Users/warren.strange/tmp/forgeops/tmp/gke/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/runtime/closure/v8.js:33:1)
```

My package deps look like this:
```
{
    "name": "gke",
    "devDependencies": {
        "@types/node": "^10.12.2"
    },
    "dependencies": {
        "@pulumi/gcp": "latest",
        "@pulumi/pulumi": "latest",
        "@pulumi/kubernetes": "latest"
    }
}
```

I did an npm update before running pulumi up

**Comment by swgillespie** [comment]
@wstrange I believe this happens because `pulumi/kubernetes` depends on an [old version](https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/nodejs/package.json#L16) of the package in this repo, which does not have the fix.

We will be publishing a new package of `pulumi/kubernetes` soon and we'll update that dependency constraint.

**Comment by ellismg** [comment]
> We will be publishing a new package of pulumi/kubernetes soon and we'll update that dependency constraint.

This has been completed.  We now have `@pulumi/kubernetes@v0.17.4` which should have this fix.  The `latest` tag has been updated, so if you install dependencies again @wstrange you should pick up the new version and it won't fall over on Node 11.

If you're seeing different behavior, let us know and we can debug more.
