### ISSUE TITLE
Windows console output encoding issues

### ISSUE THREAD

**Issue by garethr** [pulumi/pulumi#2214]
Running various `pulumi` commands on Windows results in encoding issues with the output. For example:

```console
$ pulumi stack ls
[38;5;1merror: [0m[0mno Pulumi.yaml found; please run this command in a project directory[0m  
```

I get the same results whether running in `cmd.exe` or PowerShell.

```console
$ pulumi version
v0.16.4  
```

**Comment by joeduffy** [comment]
I feel like we've seen this in the past, and fixed it, so I wonder if we've regressed. It's possible I'm just misremembering and confusing this with CI scenarios, however.

/cc @CyrusNajmabadi @ellismg

**Comment by ellismg** [comment]
What build of windows are you on @garethr?

**Comment by garethr** [comment]
@ellismg 10.0.17763 Build 17763. So the October 2018 update.

**Comment by lukehoban** [comment]
@CyrusNajmabadi @ellismg In https://github.com/pulumi/pulumi/issues/2217 there is a suggestion that this issue was fixed with `0.16.5`.  Is that true?

**Comment by ellismg** [comment]
I was still seeing this in some cases, at HEAD, when I was booted into Windows earlier.  I'm going to take a look.

**Comment by CyrusNajmabadi** [comment]
What's strange is that there seems to be some mix of ansi codes, and some mix of actual colors working:

![image](https://user-images.githubusercontent.com/4564579/48814388-67f13500-ecef-11e8-8752-48286ab27a80.png)


Specifically, the text around "previewing update" is showing the codes, while we see colors elsewhere.  Either we're doing something very wonky, or our colorization lib is doing something wonky, or potentially Windows is doing something wonky :)   will have to investigate deeper.

**Comment by CyrusNajmabadi** [comment]
Pushing out.  Need more info from customer.
