### ISSUE TITLE
Pulumi v0.17.10 no longer works with local backend on windows

### ISSUE THREAD

**Issue by FraserWaters-GR** [pulumi/pulumi#2693]
Trying to do a local login on windows leads to errors that the bucket url can't be parsed.

e.g.

    $ pulumi login --local
    error: problem logging in: unable to open bucket file://C:%!C(MISSING)Users%!C(MISSING)fraserw: open blob.Bucket: parse file://C:%!C(MISSING)Users%!C(MISSING)fraserw: invalid URL escape "%!C(MISSING)"

    $ pulumi login file://E:/Pulumi
    error: problem logging in: unable to open bucket file://E:%!C(MISSING)Pulumi: open blob.Bucket: parse file://E:%!C(MISSING)Pulumi: invalid URL escape "%!C(MISSING)"

**Comment by FraserWaters-GR** [comment]
Ping @Place1, you might have an idea what's happening here? Guessing a url parser somewhere is getting confused by Windows-isms.

**Comment by FraserWaters-GR** [comment]
For comparison on v0.17.4:

    $ pulumi login file://E:/Pulumi
    Logged into *** as ***\fraserw (file://E:/Pulumi)

**Comment by CyrusNajmabadi** [comment]
@FraserWaters-GR very sorry about this.  It's definitely due to a change I made recently to allow you to pass things like `s3://` paths so you could save your state to your own cloud storage backend (https://github.com/pulumi/pulumi/pull/2455).  I'll try to figure out a way to easily fix this for windows asap.

**Comment by CyrusNajmabadi** [comment]
Hi @FraserWaters-GR I believe i've fixed the issue, and our CI system was able to at least validate that `file://~` is working properly on windows.  I'm hoping your full paths work as well.  I'm producing a v0.17.10 release that you can use that should fix this.  

Can you try this out tomorrow to see if the problem is rectified for you?  Thanks!

**Comment by Frassle** [comment]
This still doesn't seem to be working. It says I can login in now but I don't think the stack files are being created correctly:
```
>pulumi login file://D:/pulumi
Logged into Ibasa-PC as Ibasa-PC\Fraser (file:///D:/pulumi)
    
>pulumi stack init test
>dir D:\pulumi
Volume in drive D is Data
Volume Serial Number is C0E3-BB60

 Directory of D:\pulumi

05/05/2019  11:46    <DIR>          .
05/05/2019  11:46    <DIR>          ..
05/05/2019  11:46                71 .pulumi__0x5c__stacks__0x5c__test.json
05/05/2019  11:46               212 .pulumi__0x5c__stacks__0x5c__test.json.attrs

05/05/2019  11:45                71 .pulumi__0x5c__stacks__0x5c__test.json.bak
05/05/2019  11:45               212 .pulumi__0x5c__stacks__0x5c__test.json.bak.a
ttrs
               4 File(s)            566 bytes
               2 Dir(s)  1,036,497,793,024 bytes free
```

0x5c is backslash.

Also it won't let me login with backslashes in the path
```
>pulumi login file://D:\pulumi
Manage your ←[4m←[1mPulumi stacks←[0m by logging in.
Run `pulumi login --help` for alternative login options.
Enter your access token:
```

**Comment by CyrusNajmabadi** [comment]
> This still doesn't seem to be working. It says I can login in now but I don't think the stack files are being created correctly:

Darn :-/   

Looks like this will have to get more attention to have things work better on Windows.  Sorry about that.  @ellismg since i'm OOF for the next two weeks, is this something you might be able to look at (or reassign)?  

--

Note: It's certainly not desirable that these files are not being put into folders.  But i'm curious if it's actually broken or not.  As long as the reads/writes are properly mapping to those `xxx__0x5___yyy` dirs, i imagine it might actually just work.

Not that we shouldn't fix this.  But i'm curious if this is a total blocker for you, or if you can get by, but it's just not a pleasant state to be in.

Thanks!

**Comment by Frassle** [comment]
It's kinda working. It seems I can init/update/destroy ok but "stack ls" returns nothing (not even the currently selected stack. More worrying is I doubt this will read currently existing stacks (can't check at home), and any stacks made with this will break once the backslash escaping is fixed.

We might be switching from file:// to s3:// which would hopefully allow us to use 17.9 ok, else we'll just stay on 17.8 until this is fixed (a shame because I got the PULUMI_SKIP_UPDATE_CHECK in 17.9 which would be useful for us).

**Comment by pjoe** [comment]
Ran into same issue :S

**Comment by pjoe** [comment]
FWIW: When trying with 0.17.10 I get this kind of error:
```
pulumi up
error: failed to load checkpoint: blob (code=NotFound): CreateFile C:\Users\user\.pulumi__0x5c__stacks__0x5c__dev.json: The system cannot find the file specified.
```

**Comment by rtkelly13** [comment]
I've just tried v0.17.12 and the same error is still happening
