### ISSUE TITLE
Outputting an object with a secret marks the entire object as a secret

### ISSUE THREAD

**Issue by jeffijoe** [pulumi/pulumi#2756]
I was trying to output an object map of my clusters and their information along with some secrets:

```ts
export const clusters = {
  'us-east1': {
    ...someCluster,
    someSecret: pulumi.secret('shhh')
  }
}
```

The output becomes `cluster: [secret]`.

I would expect only the secret props to be omitted in the output.

**Comment by ellismg** [comment]
Hi @jeffijoe,sorry for the delayed response.

I believe this issue should be fixed in the latest version of the CLI (we have been making fixes in this area over since this specific issue was opened).  I wrote the following small program, that should mimic what you are doing here:

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const cluster = new aws.ecs.Cluster("test-cluster");

export const clusters = {
    'us-east1': {
        ...cluster,
        someSecret: pulumi.secret("shh"),    
    }
};
```

(sorry, I was not sure what the type of `someCluster` was, so I just picked a ecs.Cluster)

When doing an update, I see things behave as expected:

```
[matell@matell pulumi-2756]$ pulumi version
v0.17.27
[matell@matell pulumi-2756]$ pulumi update --skip-preview
Updating (dev):

     Type                 Name             Status      
 +   pulumi:pulumi:Stack  pulumi-2756-dev  created     
 +   └─ aws:ecs:Cluster   test-cluster     created     
 
Outputs:
    clusters: {
        us-east1: {
            arn       : "arn:aws:ecs:us-west-2:153052954103:cluster/test-cluster-9428df4"
            id        : "arn:aws:ecs:us-west-2:153052954103:cluster/test-cluster-9428df4"
            name      : "test-cluster-9428df4"
            someSecret: "[secret]"
            urn       : "urn:pulumi:dev::pulumi-2756::aws:ecs/cluster:Cluster::test-cluster"
        }
    }

Resources:
    + 2 created

Duration: 5s
```

If you're still hitting this, can you re-open the issue and let me know what version of the CLI and `@pulumi/pulumi` package you are using?  Thanks!

**Comment by joaoh821C** [comment]
I am sorry to be the one to say this guys, but this issue is still happening. At least with the v.14.1 version.

I have this chunk of code:
```
const clouddnsKubeSecret = new kubernetes.core.v1.Secret("clouddns", {
  metadata: {
    name: "cert-manager-credentials",
    namespace: "kube-system"
  },
  data:{
    "gcp-dns-admin.json": atob(clouddnsServiceAccountKey.privateKey.apply(privateKey => `${privateKey}`))
  }
}, {
  dependsOn: clouddnsServiceAccountKey
});
```
And when I try  exposing the name as an output I still get `[secret]`
```
export const clouddnsKubeSecretName = clouddnsKubeSecret.metadata.name
- clouddnsKubeSecretName      : "[secret]"
```

**Comment by AMKamel** [comment]
I am still facing the same issue also till now v3.37.2

**Comment by Obi-Dann** [comment]
Facing it as well on pulumi@3.38.0. Got a very simple code to replicating this issue:
```js
const { secret, output, isSecret } = require('@pulumi/pulumi');

const test = output({
    secret: secret('super secret'),
});

isSecret(test).then(x => console.log('secret?', x)); // output: secret? true
```

**Comment by AMKamel** [comment]
Will you consider reopening this @ellismg @lukehoban ?

**Comment by KDanisme** [comment]
I'm also experiencing this issue with the latest pulumi version
