### ISSUE TITLE
Pulumi CLI blocks asking for config passphrase on CI server

### ISSUE THREAD

**Issue by oliverholliday** [pulumi/pulumi#2758]
It's the first time I've used the encrypting secrets and it's sat at requesting a password on an Azure DevOps CI agent - in all other instances it's correctly judged that it's in non-interactive mode.

**Comment by ellismg** [comment]
Thanks for opening this.  We should be able to make it fail gracefully and tell you to set the `PULUM_CONFIG_PASSPHRASE` environment variable instead.

**Comment by Place1** [comment]
This is a blocker for us :( @ellismg will this be fixed in the next release? I'm not sure if I should wait or downgrade.

**Comment by Place1** [comment]
@ellismg I forgot to mention in my previous comment that `PULUMI_CONFIG_PASSPHRASE=""` wouldn't work because pulumi uses `os.GetEnv` which treats undefined and "" environment variables the same

my above PR solves that issue.

**Comment by nvgoldin** [comment]
I still get this error when using `pulumi/pulumi` image on dockerhub, should I take a different version?
