### ISSUE TITLE
Duplicate output with pulumi v1.3.2

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#3374]
Pulumi v1.3.2 causes duplicate output in `preview` and `up` when a policy pack is applied via the Pulumi Console. See below for multiple rows of `Type                 Name ...` and resource diff data. 

This does not occur with `v1.3.1`. See below for output from both versions.

#### 1.3.2
```
% pulumi version
v1.3.2
% pulumi preview
Previewing update (dev):

     Type                 Name                       Plan                   Info
     Type                 Name                       Plan        Info
     pulumi:pulumi:Stack  demo-aws-ts-webserver-dev  running.
 +-  └─ aws:ec2:Instance  web-server                 replace     [diff: ~associatePublicIpAddress,tags]; mandatory: [required-name     Type                 Name                       Plan                Info
     Type                 Name                       Plan        Info
     pulumi:pulumi:Stack  demo-aws-ts-webserver-dev  running.
     pulumi:pulumi:Stack  demo-aws-ts-webserver-dev              1 error
 +-  └─ aws:ec2:Instance  web-server                 replace     [diff: ~associatePublicIpAddress,tags]; 1 error; 1 warning

Diagnostics:
  aws:ec2:Instance (web-server):
    advisory: [discouraged-ec2-public-ip-address] Associating public IP addresses is discouraged.
    observed value 'true' was expected to == 'false'
    mandatory: [required-name-tag] A 'Name' tag is required.
    Name tag must be defined.

  pulumi:pulumi:Stack (demo-aws-ts-webserver-dev):
    error: preview failed

Outputs:
  + instanceIp: output<string>

Permalink: https://app.pulumi.com/clstokes/demo-aws-ts-webserver/dev/previews/49a39bab-4f84-4d8d-a358-cbe260dec6d8
```

#### 1.3.1
```
% ~/Downloads/pulumi-v1.3.1/pulumi version
v1.3.1
% ~/Downloads/pulumi-v1.3.1/pulumi preview
Previewing update (dev):

     Type                 Name                       Plan        Info
     pulumi:pulumi:Stack  demo-aws-ts-webserver-dev              1 error
 +-  └─ aws:ec2:Instance  web-server                 replace     [diff: ~associatePublicIpAddress,tags]; 1 error; 1 warning

Diagnostics:
  pulumi:pulumi:Stack (demo-aws-ts-webserver-dev):
    error: preview failed

  aws:ec2:Instance (web-server):
    advisory: [discouraged-ec2-public-ip-address] Associating public IP addresses is discouraged.
    observed value 'true' was expected to == 'false'
    mandatory: [required-name-tag] A 'Name' tag is required.
    Name tag must be defined.

Outputs:
  + instanceIp: output<string>

Permalink: https://app.pulumi.com/clstokes/demo-aws-ts-webserver/dev/previews/6c94ca8b-affd-49e8-89ab-f244f87965e4
%
```

**Comment by justinvp** [comment]
@pgavlin, moved to `pulumi/pulumi` repo and assigning to you as this appears to be a broader regression that doesn't just impact output when policy is applied (see Cameron's comments above).

**Comment by nesl247** [comment]
Getting this on 1.3.4:

![image](https://user-images.githubusercontent.com/1037526/67300611-3b740900-f4bc-11e9-8c68-286fa3640e33.png)

**Comment by justinvp** [comment]
Thanks @nesl247. This should be fixed in master (by #3385) so closing this issue. I believe we're planning a release soon that contains the fix. cc @pgavlin.

**Comment by clstokes** [comment]
This is still occurring in 1.4.0 (both cli and `@pulumi/pulumi`). It seems to be related to StackReference usage. I'm able to reproduce this with https://github.com/pulumi/examples/tree/master/aws-ts-stackreference/team.

```
clstokes@Camerons-MacBook-Pro team % pulumi version
v1.4.0
clstokes@Camerons-MacBook-Pro team % pulumi up -y
Previewing update (dev):

     Type                 Name                            Plan       Info
 +   pulumi:pulumi:Stack  aws-ts-stackreference-team-dev  create.    read pulumi:pulumi:StackReference clstokes/aws-ts-stackreference-departmen +   pulumi:pulumi:Stack  aws-ts-stackreference-team-dev  create.    read pulumi:pulumi:StackReference clstokes/aws-ts-stackreference-company/d     Type                 Name                            Plan
 +   pulumi:pulumi:Stack  aws-ts-stackreference-team-dev  create
 +   └─ aws:ec2:Instance  tagged                          create

Resources:
    + 2 to create

Updating (dev):

     Type                 Name                            Status       Info
     Type                 Name                            Status
 +   pulumi:pulumi:Stack  aws-ts-stackreference-team-dev  created
 +   └─ aws:ec2:Instance  tagged                          created

Outputs:
    instanceId  : "i-089715dc6b3e45e6a"
    instanceTags: {
        Managed By: "Pulumi"
        company   : "ACME v3"
        department: "E-Commerce"
        team      : "Frontend"
    }

Resources:
    + 2 created

Duration: 28s

Permalink: https://app.pulumi.com/clstokes/aws-ts-stackreference-team/dev/updates/17
clstokes@Camerons-MacBook-Pro team %
```

**Comment by clstokes** [comment]
This also happens with https://github.com/pulumi/examples/tree/master/aws-ts-static-website which does not use stack references:

(scroll right in the code block to see all of it)
```
clstokes@Camerons-MacBook-Pro aws-ts-static-website % pulumi preview
Previewing update (clstokes-aws-ts-static-website):

     Type                 Name                                           Plan       Info
 +   pulumi:pulumi:Stack  static-website-clstokes-aws-ts-static-website  create.    Syncing contents from local disk at /Users/clstokes/go/src/ +   pulumi:pulumi:Stack  static-website-clstokes-aws-ts-static-website  create..   Syncing contents from local disk at /Users/clstokes/go/src/ +   pulumi:pulumi:Stack  static-website-clstokes-aws-ts-static-website  create...  Syncing contents from local disk at /Users/clstokes/go/src/ +   pulumi:pulumi:Stack  static-website-clstokes-aws-ts-static-website  create     Syncing contents from local disk at /Users/clstokes/go/src/     Type                     Name                                           Plan       Info
 +   pulumi:pulumi:Stack      static-website-clstokes-aws-ts-static-website  create.    Syncing contents from local disk at /Users/clstokes/go/ +   pulumi:pulumi:Stack      static-website-clstokes-aws-ts-static-website  create..   Syncing contents from local disk at /Users/clstokes/go/     Type                       Name                                           Plan       Info
     Type                              Name                                           Plan       Info
 +   pulumi:pulumi:Stack               static-website-clstokes-aws-ts-static-website  create...  Syncing contents from local disk at /Users/cls +   pulumi:pulumi:Stack               static-website-clstokes-aws-ts-static-website  create     1 message
 +   ├─ pulumi:providers:aws           east                                           create
 +   ├─ aws:s3:Bucket                  contentBucket                                  create
 +   │  ├─ aws:s3:BucketObject         404.html                                       create
 +   │  └─ aws:s3:BucketObject         index.html                                     create
 +   ├─ aws:s3:Bucket                  requestLogs                                    create
 +   ├─ aws:acm:Certificate            certificate                                    create
 +   ├─ aws:route53:Record             feb17.cameronstokes.xyz-validation             create
 +   ├─ aws:acm:CertificateValidation  certificateValidation                          create
 +   ├─ aws:cloudfront:Distribution    cdn                                            create
 +   └─ aws:route53:Record             feb17.cameronstokes.xyz                        create

Diagnostics:
  pulumi:pulumi:Stack (static-website-clstokes-aws-ts-static-website):
    Syncing contents from local disk at /Users/clstokes/go/src/github.com/pulumi/examples/aws-ts-static-website/www/

Resources:
    + 11 to create

Permalink: https://app.pulumi.com/clstokes/static-website/clstokes-aws-ts-static-website/previews/908f9f83-a778-4d3f-b87d-f786fd0aac73
clstokes@Camerons-MacBook-Pro aws-ts-static-website %
```
