### ISSUE TITLE
Hanging preview phase of pulumi up awaiting a Docker command

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#7074]
`pulumi preview` is hanging awaiting a Docker command. There is insufficient logging to indicate what's happening, e.g. which command is executing, and  the user encountering the issue spent a lot of effort trying to isolate it.

## Expected behavior

The CLI command `pulumi up` finishes normally or with an error message. If terminated during an unusually long invocation, expect the verbose log to contain an indication which long-running operation is outstanding and not yet finished.

## Current behavior

The CLI command `pulumi up` is hanging. Unable to determine outstanding operation from the verbose log.

## Steps to reproduce

https://github.com/t0yv0/pulumi-docker-hang-repro

**Comment by t0yv0** [comment]
Possibly related https://github.com/pulumi/pulumi-aws/issues/814

**Comment by t0yv0** [comment]
@sstuddard tagging as requested

**Comment by t0yv0** [comment]
TODO possibly move or open an issue in pulumi-docker if the fix belongs there.

**Comment by EvanBoyle** [comment]
Pulumi should be run via non-interactive mode inside of a container: `pulumi up --non-interactive`

My guess is that the "hang" is pulumi waiting for input for something like stack selection. Going to close this out as using `--non-interactive` is the by-design solution here.

**Comment by sstuddard** [comment]
Pulumi was not run within a container, unsure why this was closed.

**Comment by EvanBoyle** [comment]
@sstuddard my apologies, I misread and did not see that this was related to the pulumi docker provider.

**Comment by AaronFriel** [comment]
This should be fixed in the latest Docker provider.

**Comment by mtoto** [comment]
I'm still encountering this issue, docker build basically just hangs forever. Funny enough I was able to build the image previously, but all of a sudden it stopped working. The complete absence of logging doesn't help either.

**Comment by vinceyyyyyy** [comment]
> I'm still encountering this issue, docker build basically just hangs forever. Funny enough I was able to build the image previously, but all of a sudden it stopped working. The complete absence of logging doesn't help either.

Same thing happened here. Crosswalk (awsx) worked till yesterday but not today. Tried to switch to using pulumi-docker-build but no help.

**Comment by peter-ambiorix** [comment]
I see the same issue
