### ISSUE TITLE
Go program codegen: `pulumi.AnyArray` should be `pulumi.Array`

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#8072]
This was found compiling our program codegen test code. 
## Steps to reproduce

1. `cd pkg/codegen/internal/test/testdata/azure-native-pp`
2. `go build`

Expected: A clean compile
Actual: 
```
# main
./azure-native.go:14:6: cannot use network.ForwardingConfiguration{...} (type network.ForwardingConfiguration) as type pulumi.Input in field value:
	network.ForwardingConfiguration does not implement pulumi.Input (missing ElementType method)
./azure-native.go:16:7: cannot use network.SubResource{...} (type network.SubResource) as type *network.SubResource in field value
./azure-native.go:17:8: cannot use "/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/frontDoors/frontDoor1/backendPools/backendPool1" (type string) as type *string in field value
./azure-native.go:28:5: cannot use []cdn.DeliveryRuleArgs{...} (type []cdn.DeliveryRuleArgs) as type cdn.DeliveryRuleArrayInput in field value:
	[]cdn.DeliveryRuleArgs does not implement cdn.DeliveryRuleArrayInput (missing ElementType method)
./azure-native.go:29:6: cannot use &cdn.DeliveryRuleArgs{...} (type *cdn.DeliveryRuleArgs) as type cdn.DeliveryRuleArgs in slice literal
./azure-native.go:30:16: undefined: pulumi.AnyArray
./azure-native.go:59:19: undefined: pulumi.AnyArray
```

This issue addresses the bottom 2 lines.

**Comment by ringods** [comment]
@iwahbe the docs remain wrong for Go. I had another customer report on this. How much work would it be to change this? If you can point me to the place in the code where the wrong type is generated, I'll create a PR to have this fixed.

**Comment by tgummerer** [comment]
This was fixed in https://github.com/pulumi/pulumi/pull/14299, but didn't autoclose because I had a typo there.

**Comment by mikhailshilkov** [comment]
@tgummerer I thought this issue should close https://github.com/pulumi/pulumi-azure-native/issues/1922 but even after the code change, the example still doesn't compile. Repro:

1. Got to https://www.pulumi.com/registry/packages/azure-native/api-docs/network/firewallpolicyrulecollectiongroup/
2. Copy-paste the top Go example
3. Use azure-native v2.16.0
4. Compile the program

I get
> cannot use network.FirewallPolicyNatRuleCollection{…} (value of type network.FirewallPolicyNatRuleCollection) as "github.com/pulumi/pulumi/sdk/v3/go/internal".Input value in array or slice literal: network.FirewallPolicyNatRuleCollection does not implement "github.com/pulumi/pulumi/sdk/v3/go/internal".Input (missing method ElementType)

Is that a different issue?

**Comment by tgummerer** [comment]
Yes, I believe that is a different issue.  It looks to me like https://github.com/pulumi/pulumi-azure-native/issues/1922 is actually two different issue, one being the `AnyArray` issue that was fixed here, while the other issue seems to be what's described in https://github.com/pulumi/pulumi/issues/10834.
