### ISSUE TITLE
Experimental Update plans fails with "panic: fatal: An assertion has failed" when using StackReference

### ISSUE THREAD

**Issue by tedchang77** [pulumi/pulumi#9247]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

using a plan to do an pulumi up that has a pulumi stackreference fails with a panic message.

### Steps to reproduce

1. pulumi preview --save-plan plan.json
2. pulumi up --plan=plan.json --logtostderr -v9

pulumi program to reproduce:
```
import * as k8s from "@pulumi/kubernetes";
import * as kx from "@pulumi/kubernetesx";
import * as pulumi from "@pulumi/pulumi";

const gkeStack = new pulumi.StackReference("telushealth/gke/dev");
const appLabels = { app: "nginx" };
const deployment = new k8s.apps.v1.Deployment("nginx", {
    spec: {
        selector: { matchLabels: appLabels },
        replicas: 1,
        template: {
            metadata: { labels: appLabels },
            spec: { containers: [{ name: "nginx", image: "nginx" }] }
        }
    }
});
export const name = deployment.metadata.name;
```

Expected: plan to be applied to pulumi up
Actual: cli crashes with panic message

```
panic: fatal: An assertion has failed

goroutine 47 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*ResourcePlan).checkGoal(0x184ce40, 0xc001e464c0, 0xc001e464c0, 0x3d)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/plan.go:479 +0xf94
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).generateSteps(0xc000859d40, {0x7fef240b3168, 0xc00139b4f0})
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:471 +0x16cb
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).GenerateSteps(0xc000859d40, {0x7fef240b3168, 0xc00139b4f0})
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:186 +0x46
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).handleSingleEvent(0xc000a00570, {0x1e77f20, 0xc00139b4f0})
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:413 +0xe5
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute.func3(0xc0013df440, 0xc000a00570, 0xc000ab2d50, {0x1ea9c50, 0xc00150f000}, 0x0, 0x0, {0x1ea9cf8, 0xc0007b7080})
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:250 +0x273
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute(0xc000a00570, {0x1ea9cf8, 0xc0007b7080}, {{0x7fef23f37018, 0xc00140e000}, 0x7fffffff, 0x0, 0x0, {0x2cb4720, 0x0, ...}, ...}, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:266 +0x95f
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Deployment).Execute(0xc000566420, {0x1ea9cf8, 0xc0007b7080}, {{0x7fef23f37018, 0xc00140e000}, 0x7fffffff, 0x0, 0x0, {0x2cb4720, 0x0, ...}, ...}, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:447 +0xd0
github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run.func1()
        /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:269 +0x250
created by github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run
        /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:252 +0x371

```

**Comment by tedchang77** [comment]
@Frassle we are currently using stack references to create our k8s provider that we pass to our k8s resources:
`const provider = new k8s.Provider("k8s", { kubeconfig: gkeStack.getOutput("kubeConfig"), namespace: config.namespace });`
do you have an idea of how long it will be before there is a fix? depending on timelines we have a workaround where we can use the ambient provider - understand that this is not the best solution- instead of explicitly creating the k8s provider. thanks!

**Comment by Frassle** [comment]
I'll work on this on Monday, hopefully it's a simple fix.

**Comment by Frassle** [comment]
Tracked down that I think this is due to Check returning an error and us still trying to store the resource in the plan and check it against the plan.

**Comment by Frassle** [comment]
I think the merged PR should fix this, will be included in the release this Wednesday. Try it out, if there's still issues re-open this ticket and let us know.

**Comment by tedchang77** [comment]
@Frassle i've updated to the latest pulumi and i'm still seeing the same error:
```
tc@L109033:~/thx/thxcs-shared-services/pulumi-plan$ echo $PULUMI_EXPERIMENTAL
true
tc@L109033:~/thx/thxcs-shared-services/pulumi-plan$ pulumi version
v3.27.0
tc@L109033:~/thx/thxcs-shared-services/pulumi-plan$ pulumi preview --save-plan plan.json
Previewing update (dev)

View Live: https://app.pulumi.com/telushealth/pulumi-plan/dev/previews/929e6294-a404-4f28-9cf4-b89d1fadd902

     Type                              Name             Plan       
 +   pulumi:pulumi:Stack               pulumi-plan-dev  create     
 +   └─ kubernetes:apps/v1:Deployment  nginx            create     
 
Resources:
    + 2 to create

Update plan written to 'plan.json'
Run `pulumi up --plan='plan.json'` to constrain the update to the operations planned by this preview
tc@L109033:~/thx/thxcs-shared-services/pulumi-plan$ pulumi up --plan=plan.json --logtostderr -v9
Previewing update (dev)

I0326 23:39:36.161822    6291 backend.go:938] Stack dev being updated to version 6
View Live: https://app.pulumi.com/telushealth/pulumi-plan/dev/previews/6059e834-8179-48c3-aba8-f0dd03753aaa

I0326 23:39:36.543605    6291 update.go:192] *** Starting Update(preview=true) ***
I0326 23:39:36.544583    6291 plugins.go:76] gatherPluginsFromProgram(): gathering plugins from language host
I0326 23:39:36.815925    6291 plugins.go:1057] GetPluginPath(language, nodejs, <nil>): found on $PATH /home/tc/.pulumi/bin/pulumi-language-nodejs
I0326 23:39:36.816765    6291 plugin.go:126] Launching plugin 'nodejs' from '/home/tc/.pulumi/bin/pulumi-language-nodejs' with args: -root=/home/tc/thx/thxcs-shared-services/pulumi-plan,127.0.0.1:34221
I0326 23:39:37.181442    6291 langruntime_plugin.go:204] langhost[nodejs].GetPluginInfo() executing
I0326 23:39:37.182330    6291 langruntime_plugin.go:112] langhost[nodejs].GetRequiredPlugins(proj=pulumi-plan,pwd=/home/tc/thx/thxcs-shared-services/pulumi-plan,program=.) executing
I0326 23:39:37.217979    6291 langruntime_plugin.go:154] langhost[nodejs].GetRequiredPlugins(proj=pulumi-plan,pwd=/home/tc/thx/thxcs-shared-services/pulumi-plan,program=.) success: #versions=1
I0326 23:39:37.218156    6291 plugins.go:88] gatherPluginsFromProgram(): plugin nodejs <nil> () is required by language host
I0326 23:39:37.218699    6291 plugins.go:88] gatherPluginsFromProgram(): plugin kubernetes 3.17.0 () is required by language host
I0326 23:39:37.219112    6291 plugins.go:100] gatherPluginsFromSnapshot(): gathering plugins from snapshot
I0326 23:39:37.219803    6291 plugins.go:137] ensurePluginsAreInstalled(): beginning
I0326 23:39:37.255019    6291 plugins.go:1057] GetPluginPath(language, nodejs, <nil>): found on $PATH /home/tc/.pulumi/bin/pulumi-language-nodejs
I0326 23:39:37.255213    6291 plugins.go:142] ensurePluginsAreInstalled(): plugin nodejs <nil> already installed
I0326 23:39:37.292259    6291 plugins.go:1097] GetPluginPath(resource, kubernetes, 3.17.0): enabling new plugin behavior
I0326 23:39:37.292430    6291 plugins.go:1183] SelectCompatiblePlugin(..., kubernetes): beginning
I0326 23:39:37.292738    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.0.0: semver mismatch
I0326 23:39:37.292881    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.1.1: semver mismatch
I0326 23:39:37.293175    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.3.0: semver mismatch
I0326 23:39:37.293459    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.4.0: semver mismatch
I0326 23:39:37.293782    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.4.1: semver mismatch
I0326 23:39:37.294191    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.6.0: semver mismatch
I0326 23:39:37.294456    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.6.2: semver mismatch
I0326 23:39:37.294802    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.6.3: semver mismatch
I0326 23:39:37.295209    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.7.0: semver mismatch
I0326 23:39:37.295871    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.8.2: semver mismatch
I0326 23:39:37.296250    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.8.3: semver mismatch
I0326 23:39:37.296560    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.16.0: semver mismatch
I0326 23:39:37.296910    6291 plugins.go:1212] SelectCompatiblePlugin(..., kubernetes): best plugin kubernetes-3.17.0: semver match
I0326 23:39:37.297364    6291 plugins.go:1225] SelectCompatiblePlugin(..., kubernetes): selecting plugin 'kubernetes-3.17.0': best match 
I0326 23:39:37.297704    6291 plugins.go:1144] GetPluginPath(resource, kubernetes, 3.17.0): found in cache at /home/tc/.pulumi/plugins/resource-kubernetes-v3.17.0/pulumi-resource-kubernetes
I0326 23:39:37.298030    6291 plugins.go:142] ensurePluginsAreInstalled(): plugin kubernetes 3.17.0 already installed
I0326 23:39:37.298387    6291 plugins.go:157] ensurePluginsAreInstalled(): completed
I0326 23:39:37.298900    6291 plugins.go:246] computeDefaultProviderPlugins(): considering nodejs
I0326 23:39:37.299187    6291 plugins.go:249] computeDefaultProviderPlugins(): skipping nodejs, not a resource provider
I0326 23:39:37.299410    6291 plugins.go:246] computeDefaultProviderPlugins(): considering kubernetes-3.17.0
I0326 23:39:37.299780    6291 plugins.go:277] computeDefaultProviderPlugins(): plugin kubernetes-3.17.0 selected for package kubernetes (first seen)
I0326 23:39:37.300147    6291 plugins.go:283] computeDefaultProviderPlugins(): summary of default plugins:
I0326 23:39:37.300470    6291 plugins.go:285]   kubernetes      = 3.17.0
I0326 23:39:37.301091    6291 step_generator.go:1103] stepGenerator.GeneratePendingDeletes(): scanning previous snapshot for pending deletes
I0326 23:39:37.301292    6291 deployment_executor.go:440] deploymentExecutor.retirePendingDeletes(...): no pending deletions
I0326 23:39:37.301624    6291 deployment_executor.go:221] deploymentExecutor.Execute(...): waiting for incoming events
I0326 23:39:37.301223    6291 langruntime_plugin.go:165] langhost[nodejs].Run(pwd=/home/tc/thx/thxcs-shared-services/pulumi-plan,program=.,#args=0,proj=pulumi-plan,stack=dev,#config=0,dryrun=true) executing
I0326 23:39:37.301655    6291 step_executor.go:364] StepExecutor worker(-2): worker coming online
I0326 23:39:37.302317    6291 step_executor.go:364] StepExecutor worker(-2): worker waiting for incoming chains
I0326 23:39:37.753291    6291 eventsink.go:59] Registering resource: t=pulumi:pulumi:Stack, name=pulumi-plan-dev, custom=false, remote=false
I0326 23:39:37.753508    6291 eventsink.go:62] eventSink::Debug(<{%reset%}>Registering resource: t=pulumi:pulumi:Stack, name=pulumi-plan-dev, custom=false, remote=false<{%reset%}>)
I0326 23:39:37.763911    6291 eventsink.go:59] RegisterResource RPC prepared: t=pulumi:pulumi:Stack, name=pulumi-plan-dev
I0326 23:39:37.764068    6291 eventsink.go:62] eventSink::Debug(<{%reset%}>RegisterResource RPC prepared: t=pulumi:pulumi:Stack, name=pulumi-plan-dev<{%reset%}>)
I0326 23:39:37.765063    6291 source_eval.go:1072] ResourceMonitor.RegisterResource received: t=pulumi:pulumi:Stack, name=pulumi-plan-dev, custom=false, #props=0, parent=, protect=false, provider=, deps=[], deleteBeforeReplace=<nil>, ignoreChanges=[], aliases=[], customTimeouts={0 0 0}, providers=map[], replaceOnChanges=[], retainOnDelete=false
I0326 23:39:37.765332    6291 source_eval.go:167] EvalSourceIterator produced a registration: t=pulumi:pulumi:Stack,name=pulumi-plan-dev,#props=0
I0326 23:39:37.765646    6291 deployment_executor.go:225] deploymentExecutor.Execute(...): incoming event (nil? false, <nil>)
I0326 23:39:37.765965    6291 deployment_executor.go:412] deploymentExecutor.handleSingleEvent(...): received RegisterResourceEvent
I0326 23:39:37.766284    6291 step_generator.go:660] Planner decided to create 'urn:pulumi:dev::pulumi-plan::pulumi:pulumi:Stack::pulumi-plan-dev' (inputs=map[])
I0326 23:39:37.766581    6291 step_executor.go:364] StepExecutor worker(-2): worker received chain for execution
I0326 23:39:37.766892    6291 step_executor.go:364] StepExecutor worker(-2): worker waiting for incoming chains
I0326 23:39:37.766915    6291 step_executor.go:364] StepExecutor worker(0): launching oneshot worker
I0326 23:39:37.767480    6291 step_executor.go:364] StepExecutor worker(0): applying step create on urn:pulumi:dev::pulumi-plan::pulumi:pulumi:Stack::pulumi-plan-dev (preview true)

I0326 23:39:37.767797    6291 step_executor.go:364] StepExecutor worker(0): step create on urn:pulumi:deI0326 23:39:37.767883    6291 source_eval.go:1162] ResourceMonitor.RegisterResource operation finished: t=pulumi:pulumi:Stack, urn=urn:pulumi:dev::pulumi-plan::pulumi:pulumi:Stack::pulumi-plan-dev, #outs=0
 +   pulumi:pulumi:Stack  pulumi-plan-dev  create..   
I0326 23:39:37.777968    6291 eventsink.go:59] RegisterResource RPC finished: resource:pulumi-plan-dev[pulumi:pulumi:Stack]; err: null, resp: urn:pulumi:dev::pulumi-plan::pulumi:pulumi:Stack::pulumi-plan-dev,,,,
I0326 23:39:37.778177    6291 eventsink.go:62] eventSink::Debug(<{%reset%}>RegisterResource RPC finished: resource:pulumi-plan-dev[pulumi:pulumi:Stack]; err: null, resp: urn:pulumi:dev::pulumi-plan::pulumi:pulumi:Stack::pulumi-plan-dev,,,,<{%reset%}>)
I0326 23:39:37.935381    6291 eventsink.go:59] Running program '/home/tc/thx/thxcs-shared-services/pulumi-plan' in pwd '/home/tc/thx/thxcs-shared-services/pulumi-plan' w/ args: 
I0326 23:39:37.935579    6291 eventsink.go:62] eventSink::Debug(<{%reset%}>Running program '/home/tc/thx/thxcs-shared-services/pulumi-plan' in pwd '/home/tc/thx/thxcs-shared-services/pulumi-plan' w/ args: <{%reset%}>)
I0326 23:39:37.942490    6291 source_eval.go:600] parseProviderRequest(pulumi): semver version is the empty string
I0326 23:39:37.942526    6291 source_eval.go:345] handling default provider request for package kubernetes-3.17.0
I0326 23:39:37.943051    6291 source_eval.go:403] checking if kubernetes-3.17.0 should be denied
I0326 23:39:37.943359    6291 source_eval.go:437] Did not find a config for 'pulumi'
I0326 23:39:37.943689    6291 source_eval.go:293] newRegisterDefaultProviderEvent(kubernetes-3.17.0): using version 3.17.0 from request
I0326 23:39:37.942564    6291 eventsink.go:59] Reading resource: id=telushealth/gke/dev, t=pulumi:pulumi:StackReference, name=telushealth/gke/dev
I0326 23:39:37.944261    6291 eventsink.go:62] eventSink::Debug(<{%reset%}>Reading resource: id=telushealth/gke/dev, t=pulumi:pulumi:StackReference, name=telushealth/gke/dev<{%reset%}>)
I0326 23:39:37.943934    6291 source_eval.go:312] newRegisterDefaultProviderEvent(kubernetes-3.17.0): no pluginDownloadURL specified, falling back to default pluginDownloadURL
I0326 23:39:37.944888    6291 source_eval.go:320] newRegisterDefaultProviderEvent(kubernetes-3.17.0): default pluginDownloadURL miss, sending empty string to engine
I0326 23:39:37.945053    6291 source_eval.go:378] waiting for default provider for package kubernetes-3.17.0
I0326 23:39:37.945129    6291 source_eval.go:167] EvalSourceIterator produced a registration: t=pulumi:providers:kubernetes,name=default_3_17_0,#props=1
I0326 23:39:37.945608    6291 deployment_executor.go:225] deploymentExecutor.Execute(...): incoming event (nil? false, <nil>)
I0326 23:39:37.945899    6291 deployment_executor.go:412] deploymentExecutor.handleSingleEvent(...): received RegisterResourceEvent
I0326 23:39:37.945947    6291 registry.go:260] ProviderRegistry.Check(urn:pulumi:dev::pulumi-plan::pulumi:providers:kubernetes::default_3_17_0) executing (#olds=1,#news=1)
I0326 23:39:37.945991    6291 eventsink.go:59] Registering resource: t=kubernetes:apps/v1:Deployment, name=nginx, custom=true, remote=false
I0326 23:39:37.946225    6291 eventsink.go:62] eventSink::Debug(<{%reset%}>Registering resource: t=kubernetes:apps/v1:Deployment, name=nginx, custom=true, remote=false<{%reset%}>)
I0326 23:39:37.948291    6291 eventsink.go:59] RegisterResource RPC prepared: t=kubernetes:apps/v1:Deployment, name=nginx
I0326 23:39:37.948431    6291 eventsink.go:62] eventSink::Debug(<{%reset%}>RegisterResource RPC prepared: t=kubernetes:apps/v1:Deployment, name=nginx<{%reset%}>)
I0326 23:39:37.950375    6291 eventsink.go:59] ReadResource RPC prepared: id=telushealth/gke/dev, t=pulumi:pulumi:StackReference, name=telushealth/gke/dev
I0326 23:39:37.950535    6291 eventsink.go:62] eventSink::Debug(<{%reset%}>ReadResource RPC prepared: id=telushealth/gke/dev, t=pulumi:pulumi:StackReference, name=telushealth/gke/dev<{%reset%}>)
I0326 23:39:37.990673    6291 plugins.go:1097] GetPluginPath(resource, kubernetes, 3.17.0): enabling new plugin behavior
I0326 23:39:37.990873    6291 plugins.go:1183] SelectCompatiblePlugin(..., kubernetes): beginning
I0326 23:39:37.991185    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.0.0: semver mismatch
I0326 23:39:37.991471    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.1.1: semver mismatch
I0326 23:39:37.991753    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.3.0: semver mismatch
I0326 23:39:37.992044    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.4.0: semver mismatch
I0326 23:39:37.992399    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.4.1: semver mismatch
I0326 23:39:37.992736    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.6.0: semver mismatch
I0326 23:39:37.993084    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.6.2: semver mismatch
I0326 23:39:37.993429    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.6.3: semver mismatch
I0326 23:39:37.993780    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.7.0: semver mismatch
I0326 23:39:37.994131    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.8.2: semver mismatch
I0326 23:39:37.994537    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.8.3: semver mismatch
I0326 23:39:37.994903    6291 plugins.go:1216] SelectCompatiblePlugin(..., kubernetes): skipping plugin kubernetes-3.16.0: semver mismatch
I0326 23:39:37.995272    6291 plugins.go:1212] SelectCompatiblePlugin(..., kubernetes): best plugin kubernetes-3.17.0: semver match
I0326 23:39:37.995633    6291 plugins.go:1225] SelectCompatiblePlugin(..., kubernetes): selecting plugin 'kubernetes-3.17.0': best match 
I0326 23:39:37.996014    6291 plugins.go:1144] GetPluginPath(resource, kubernetes, 3.17.0): found in cache at /home/tc/.pulumi/plugins/resource-kubernetes-v3.17.0/pulumi-resource-kubernetes
I0326 23:39:37.996452    6291 plugin.go:126] Launching plugin 'kubernetes (resource)' from '/home/tc/.pulumi/plugins/resource-kubernetes-v3.17.0/pulumi-resource-kubernetes' with args: 127.0.0.1:34221
I0326 23:39:38.063356    6291 provider_plugin.go:1434] Provider[kubernetes, 0xc000984780].GetPluginInfo() executing
I0326 23:39:38.063992    6291 provider_plugin.go:180] Provider[kubernetes, 0xc000984780].CheckConfig(urn:pulumi:dev::pulumi-plan::pulumi:providers:kubernetes::default_3_17_0) executing (#olds=1,#news=1)
I0326 23:39:38.064069    6291 rpc.go:74] Marshaling property for RPC[Provider[kubernetes, 0xc000984780].CheckConfig(urn:pulumi:dev::pulumi-plan::pulumi:providers:kubernetes::default_3_17_0).olds]: version={3.17.0}
I0326 23:39:38.064277    6291 rpc.go:74] Marshaling property for RPC[Provider[kubernetes, 0xc000984780].CheckConfig(urn:pulumi:dev::pulumi-plan::pulumi:providers:kubernetes::default_3_17_0).news]: version={3.17.0}
I0326 23:39:38.065436    6291 rpc.go:274] Unmarshaling property for RPC[Provider[kubernetes, 0xc000984780].CheckConfig(urn:pulumi:dev::pulumi-plan::pulumi:providers:kubernetes::default_3_17_0).inputs]: version={3.17.0}
I0326 23:39:38.065568    6291 provider_plugin.go:243] Provider[kubernetes, 0xc000984780].CheckConfig(urn:pulumi:dev::pulumi-plan::pulumi:providers:kubernetes::default_3_17_0) success: inputs=#1 failures=#0
I0326 23:39:38.065873    6291 registry.go:184] setProvider(urn:pulumi:dev::pulumi-plan::pulumi:providers:kubernetes::default_3_17_0::04da6b54-80e4-46f7-96ec-b56ff0331ba9)
I0326 23:39:38.066200    6291 step_generator.go:660] Planner decided to create 'urn:pulumi:dev::pulumi-plan::pulumi:providers:kubernetes::default_3_17_0' (inputs=map[version:{3.17.0}])
I0326 23:39:38.066497    6291 step_executor.go:364] StepExecutor worker(-2): worker received chain for execution
I0326 23:39:38.066774    6291 step_executor.go:364] StepExecutor worker(-2): worker waiting for incoming chains
I0326 23:39:38.066939    6291 step_executor.go:364] StepExecutor worker(1): launching oneshot worker
I0326 23:39:38.067384    6291 step_executor.go:364] StepExecutor worker(1): applying step create on urn:pulumi:dev::pulumi-plan::pulumi:providers:kubernetes::default_3_17_0 (preview true)
I0326 23:39:38.067660    6291 registry.go:371] ProviderRegistry.Create(urn:pulumi:dev::pulumi-plan::pulumi:providers:kubernetes::default_3_17_0) executing (#news=1)
I0326 23:39:38.067903    6291 registry.go:174] GetProvider(urn:pulumi:dev::pulumi-plan::pulumi:providers:kubernetes::default_3_17_0::04da6b54-80e4-46f7-96ec-b56ff0331ba9)
I0326 23:39:38.068101    6291 provider_plugin.go:452] Provider[kubernetes, 0xc000984780].Configure() executing (#vars=1)
I0326 23:39:38.068380    6291 rpc.go:74] Marshaling property for RPC[Provider[kubernetes, 0xc000984780].Configure().inputs]: version={3.17.0}
I0326 23:39:38.068662    6291 registry.go:184] setProvider(urn:pulumi:dev::pulumi-plan::pulumi:providers:kubernetes::default_3_17_0::)
I0326 23:39:38.068914    6291 step_executor.go:364] StepExecutor worker(1): step create on urn:pulumi:dev::pulumi-plan::pulumi:providers:kubernetes::default_3_17_0 retired
I0326 23:39:38.069144    6291 source_eval.go:387] registered default provider for package kubernetes-3.17.0: urn:pulumi:dev::pulumi-plan::pulumi:providers:kubernetes::default_3_17_0
I0326 23:39:38.069330    6291 source_eval.go:345] handling default provider request for package pulumi
I0326 23:39:38.069488    6291 source_eval.go:403] checking if pulumi should be denied
I0326 23:39:38.069601    6291 source_eval.go:437] Did not find a config for 'pulumi'
I0326 23:39:38.069609    6291 source_eval.go:296] newRegisterDefaultProviderEvent(pulumi): no version specified, falling back to default version
I0326 23:39:38.069621    6291 source_eval.go:302] newRegisterDefaultProviderEvent(pulumi): default provider miss, sending nil version to engine
I0326 23:39:38.069636    6291 source_eval.go:312] newRegisterDefaultProviderEvent(pulumi): no pluginDownloadURL specified, falling back to default pluginDownloadURL
I0326 23:39:38.069649    6291 source_eval.go:320] newRegisterDefaultProviderEvent(pulumi): default pluginDownloadURL miss, sending empty string to engine
I0326 23:39:38.069673    6291 source_eval.go:378] waiting for default provider for package pulumi
I0326 23:39:38.069701    6291 source_eval.go:167] EvalSourceIterator produced a registration: t=pulumi:providers:pulumi,name=default,#props=0
I0326 23:39:38.069726    6291 deployment_executor.go:225] deploymentExecutor.Execute(...): incoming event (nil? false, <nil>)
I0326 23:39:38.069744    6291 deployment_executor.go:412] deploymentExecutor.handleSingleEvent(...): received RegisterResourceEvent
I0326 23:39:38.069347    6291 rpc.go:274] Unmarshaling property for RPC[ResourceMonitor.RegisterResource(kubernetes:apps/v1:Deployment,nginx)]: apiVersion={apps/v1}
I0326 23:39:38.069882    6291 rpc.go:274] Unmarshaling property for RPC[ResourceMonitor.RegisterResource(kubernetes:apps/v1:Deployment,nginx)]: kind={Deployment}
I0326 23:39:38.069951    6291 rpc.go:274] Unmarshaling property for RPC[ResourceMonitor.RegisterResource(kubernetes:apps/v1:Deployment,nginx)]: replicas={1}
I0326 23:39:38.070082    6291 rpc.go:274] Unmarshaling property for RPC[ResourceMonitor.RegisterResource(kubernetes:apps/v1:Deployment,nginx)]: app={nginx}
I0326 23:39:38.070367    6291 rpc.go:274] Unmarshaling property for RPC[ResourceMonitor.RegisterResource(kubernetes:apps/v1:Deployment,nginx)]: matchLabels={map[app:{nginx}]}
I0326 23:39:38.070655    6291 rpc.go:274] Unmarshaling property for RPC[ResourceMonitor.RegisterResource(kubernetes:apps/v1:Deployment,nginx)]: selector={map[matchLabels:{map[app:{nginx}]}]}
I0326 23:39:38.070944    6291 rpc.go:274] Unmarshaling property for RPC[ResourceMonitor.RegisterResource(kubernetes:apps/v1:Deployment,nginx)]: app={nginx}
I0326 23:39:38.069835    6291 registry.go:260] ProviderRegistry.Check(urn:pulumi:dev::pulumi-plan::pulumi:providers:pulumi::default) executing (#olds=0,#news=0)
I0326 23:39:38.071387    6291 registry.go:184] setProvider(urn:pulumi:dev::pulumi-plan::pulumi:providers:pulumi::default::04da6b54-80e4-46f7-96ec-b56ff0331ba9)
panic: fatal: An assertion has failed

goroutine 42 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*ResourcePlan).checkGoal(0x1855700, 0xc000ff0400, 0xc000ff0400, 0x3d)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/plan.go:479 +0xf94
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).generateSteps(0xc0006a2d80, {0x7fc7c7ff0390, 0xc0016aac30})
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:476 +0x16eb
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).GenerateSteps(0xc0006a2d80, {0x7fc7c7ff0390, 0xc0016aac30})
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_generator.go:190 +0x46
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).handleSingleEvent(0xc000fa07e0, {0x1e84980, 0xc0016aac30})
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:413 +0xe5
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute.func3(0xc000f83920, 0xc000fa07e0, 0xc000fefd00, {0x1eb6890, 0xc000f19e40}, 0x0, 0x0, {0x1eb6938, 0xc00162f410})
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:250 +0x273
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute(0xc000fa07e0, {0x1eb6938, 0xc00162f410}, {{0x7fc7c7cfabd8, 0xc0015862c0}, 0x7fffffff, 0x0, 0x0, {0x2cc8a18, 0x0, ...}, ...}, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:266 +0x95f
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Deployment).Execute(0xc001620420, {0x1eb6938, 0xc00162f410}, {{0x7fc7c7cfabd8, 0xc0015862c0}, 0x7fffffff, 0x0, 0x0, {0x2cc8a18, 0x0, ...}, ...}, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:447 +0xd0
github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run.func1()
        /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:269 +0x250
created by github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run
        /Users/runner/work/pulumi/pulumi/pkg/engine/deployment.go:252 +0x371
```

**Comment by Frassle** [comment]
Ah sorry about that! The first fix had fixed the problem that `Check` could return nil if it failed and we weren't handling that properly in planning. It seems `Check` can also return nil if it passes although I suspect that `StackReferences` are the only type it would actually do that for.

I'll see if we should either change the code to handle a nil result from Check.

**Comment by tedchang77** [comment]
@Frassle thanks for the quick fix! if i wanted to test this is there a build that i can download anywhere? or do i need to build from source?

**Comment by Frassle** [comment]
You download the builds from the last CI run on master: https://github.com/pulumi/pulumi/actions/runs/2047360090

**Comment by RazcoDev** [comment]
The ARM artifact had already expired, how can I download it anyway ?
