### ISSUE TITLE
Pulumi for python autodetect incorrect providers versions when providers list is specified

### ISSUE THREAD

**Issue by piotr-bzdyl-vertexinc** [pulumi/pulumi#9847]
### What happened?

Most of the issues I reported in #9548, has been fixed by #9802.

However, there is one more scenario that causes errors like:
```
error: no resource plugin 'pulumi-resource-random' found in the workspace at version v5.8.0 or on your $PATH, install the plugin using `pulumi plugin install resource random v5.8.0`
```

It seems that if `pulumi.ResourceOptions.providers` list is specified, the issue still occurs.

### Steps to reproduce

Use the following program to reproduce the issue:

```
$ cat requirements.txt
pulumi>=3.0.0,<4.0.0
pulumi-aws>=5.0.0,<6.0.0
pulumi-random>=4.6.0,<5.0.0

$ cat __main__.py                                                      
from typing import Optional
import pulumi
import pulumi_aws
import pulumi_random


class MyComponent(pulumi.ComponentResource):
    def __init__(self,
                 name: str,
                 opts: Optional[pulumi.ResourceOptions] = None):
        super().__init__(f'pkg:index:{type(self).__name__}', name=name, opts=opts)
        resource_opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(parent=self))

        pulumi_aws.s3.Bucket(
            name,
            bucket=name,
            opts=resource_opts,
        )

        pulumi_random.RandomString(
            name,
            length=8,
            opts=resource_opts,
        )


aws_provider = pulumi_aws.Provider('eu-west-1')

MyComponent(
    'test1',
    opts=pulumi.ResourceOptions(
        providers=[aws_provider],
    )
)
```

It results in:

```
$ pulumi preview       
Previewing update (dev)

View Live: https://app.pulumi.com/*****/pulumi-plugin-version-providers-issue/dev/previews/3bc32cea-9fb3-4fa0-904d-8b1a5e24062c

     Type                        Name                                       Plan       Info
 +   pulumi:pulumi:Stack         pulumi-plugin-version-providers-issue-dev  create     
 +   ├─ pkg:index:MyComponent    test1                                      create     
 +   ├─ pulumi:providers:aws     eu-west-1                                  create     
     └─ pulumi:providers:random  default_5_8_0                                         1 error
 
Diagnostics:
  pulumi:providers:random (default_5_8_0):
    error: no resource plugin 'pulumi-resource-random' found in the workspace at version v5.8.0 or on your $PATH, install the plugin using `pulumi plugin install resource random v5.8.0`
```

### Expected Behavior

It detects the correct provider/plugin version.

### Actual Behavior

`pulumi preview` fails with:

```
error: no resource plugin 'pulumi-resource-random' found in the workspace at version v5.8.0 or on your $PATH, install the plugin using `pulumi plugin install resource random v5.8.0`
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
>  I'm taking this and looking into if a deepcopy is the right thing to do here, as I think that should solve the nested options issue.

I think we need the deepcopy in the SDK rather than codegen. The `_get_providers` function called in the Resource base init function looks to be the culprit for this mutation. But that means we can do the deepcopy in that init method before calling `_get_providers`. Less lag time from fix to release than going through codegen, plus I think a more precise fix as anyone else using the Resource class would also need to fix around this.

**Comment by AaronFriel** [comment]
@piotr-bzdyl-vertexinc as a temporary workaround, you could do a deep copy of the resource options yourself or instantiate the resource option instead of reusing it.

We'll track a fix to the Python SDK for the next release.

**Comment by AaronFriel** [comment]
@piotr-bzdyl-vertexinc it looks like #9802 should fix this when we are able to update providers to target Pulumi, and I dug a bit deeper and implemented a more systematic fix in #9856.

**Comment by AaronFriel** [comment]
@piotr-bzdyl-vertexinc this is closed because I believe the problem is resolved in future provider releases, but that may take a week or two.

In the meantime, I believe this workaround will suffice:

```python
import copy
...
        pulumi_aws.s3.Bucket(
            name,
            bucket=name,
            opts=copy.copy(resource_opts),
        )

        pulumi_random.RandomString(
            name,
            length=8,
            opts=copy.copy(resource_opts),
        )
```

Let me know if that doesn't work!

**Comment by chris-remedy** [comment]
I'm still having this problem, or something like it, with Pulumi 3.35.3 in a clean Github Actions environment, when previewing a brand new stack:

```
Diagnostics:
    pulumi:providers:aws (default_5_4_0):
      error: no resource plugin 'pulumi-resource-aws' found in the workspace at version v5.4.0 or on your $PATH, install the plugin using `pulumi plugin install resource aws v5.4.0`
```

With requirements.txt having:
```
pulumi==3.35.3
pulumi-aws==5.9.2
pulumi-awsx==1.0.0b9
pulumi-docker==3.2.0
```
